/////////////////////////////////////////////////////////////////////
/////// Generated by tsgen. DO NOT EDIT.
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
/////// Extra TS Code:
/////////////////////////////////////////////////////////////////////

type VormaRootData = null;

export type VormaApp = {
	routes: typeof routes;
	appConfig: typeof vormaAppConfig;
	rootData: VormaRootData;
};

export const vormaAppConfig = {
	actionsRouterMountRoot: "/api/",
	actionsDynamicRune: ":",
	actionsSplatRune: "*",
	loadersDynamicRune: ":",
	loadersSplatRune: "*",
	loadersExplicitIndexSegment: "_index",
	__phantom: null as unknown as VormaApp,
} as const;

import type {
	VormaLoaderPattern,
	VormaMutationInput,
	VormaMutationOutput,
	VormaMutationPattern,
	VormaMutationProps,
	VormaQueryInput,
	VormaQueryOutput,
	VormaQueryPattern,
	VormaQueryProps,
} from "vorma/client";
import type { VormaRouteProps } from "vorma/react";

export type QueryPattern = VormaQueryPattern<VormaApp>;
export type QueryProps<P extends QueryPattern> = VormaQueryProps<VormaApp, P>;
export type QueryInput<P extends QueryPattern> = VormaQueryInput<VormaApp, P>;
export type QueryOutput<P extends QueryPattern> = VormaQueryOutput<VormaApp, P>;

export type MutationPattern = VormaMutationPattern<VormaApp>;
export type MutationProps<P extends MutationPattern> = VormaMutationProps<VormaApp, P>;
export type MutationInput<P extends MutationPattern> = VormaMutationInput<VormaApp, P>;
export type MutationOutput<P extends MutationPattern> = VormaMutationOutput<VormaApp, P>;

export type RouteProps<P extends VormaLoaderPattern<VormaApp>> = VormaRouteProps<VormaApp, P>;

/////////////////////////////////////////////////////////////////////
/////// Vorma Vite Config:
/////////////////////////////////////////////////////////////////////

import { staticPublicAssetMap } from "./filemap";
export { staticPublicAssetMap };
export type StaticPublicAsset = keyof typeof staticPublicAssetMap;

declare global {
	function waveBuildtimeURL(staticPublicAsset: StaticPublicAsset): string;
}

export const publicPathPrefix = "/";

export function waveRuntimeURL(originalPublicURL: StaticPublicAsset) {
	const url = staticPublicAssetMap[originalPublicURL] ?? originalPublicURL;
	return publicPathPrefix + url;
}

export const vormaViteConfig = {
	rollupInput: [
		"frontend/src/vorma.entry.tsx"
	],
	publicPathPrefix,
	staticPublicAssetMap,
	buildtimePublicURLFuncName: "waveBuildtimeURL",
	filemapJSONPath: "frontend/src/vorma.gen/filemap.json",
	ignoredPatterns: [
		"**/*.go",
		"**/var/folders/ty/mytxd1bs5wv5xx5qjcl0zsr80000gn/T/TestRebuildRoutesOnlysuccess_path_logs_completion1551979789/001/dist/**/*",
		"**/var/folders/ty/mytxd1bs5wv5xx5qjcl0zsr80000gn/T/TestRebuildRoutesOnlysuccess_path_logs_completion1551979789/001/dist/static/assets/private/**/*",
		"**/frontend/src/vorma.gen/**/*",
		"**/frontend/src/**/*vorma.routes.ts"
	],
	dedupeList: [
		"react",
		"react-dom"
	],
} as const;
