[workspace]
members = [
	"crates/vorma-build",
	"crates/vorma-client-wasm",
	"crates/vorma-macros",
	"crates/vorma-matcher",
	"crates/vorma",
	"crates/vorma-tasks",
	"examples/minimal",
	"tests/framework",
	"xtask",
]
resolver = "3"

[workspace.package]
edition = "2024"
homepage = "https://vorma.dev"
license = "MIT"
repository = "https://github.com/vormadev/vorma"
version = "0.86.0-pre.0"

[workspace.dependencies]
axum = "0.8"
base64 = "0.22"
blake3 = "1"
bytes = "1"
cookie = "0.18"
data-encoding = "2"
futures-util = "0.3"
getrandom = "0.3"
globset = "0.4"
html-escape = "0.2"
http = "1"
http-body = "1"
http-body-util = "0.1"
libc = "0.2"
lightningcss = "1.0.0-alpha.71"
lru = "0.12"
mime = "0.3"
mime_guess = "2"
multer = "3"
notify = "8.2"
paranoid = { version = "0.0.0-pre.1", default-features = false }
path-clean = "1"
path-slash = "0.2"
pathdiff = "0.2"
percent-encoding = "2"
proc-macro2 = "1"
quote = "1"
same-file = "1"
serde = "1"
serde_json = "1"
serde_urlencoded = "0.7"
sha2 = "0.10"
syn = "2"
tokio = "1"
tower = "0.5"
tower-http = "0.6"
tower-layer = "0.3"
tower-service = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
ureq = { version = "3", default-features = false }
url = "2"
vorma = { path = "crates/vorma", version = "0.86.0-pre.0" }
vorma-build = { path = "crates/vorma-build", version = "0.86.0-pre.0" }
vorma-macros = { path = "crates/vorma-macros", version = "0.86.0-pre.0" }
vorma-matcher = { path = "crates/vorma-matcher", version = "0.86.0-pre.0" }
vorma-tasks = { path = "crates/vorma-tasks", version = "0.86.0-pre.0" }
walkdir = "2"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
