package tsgen

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"

	"github.com/vormadev/vorma/kit/fsutil"
	"github.com/vormadev/vorma/kit/jsonutil"
	"github.com/vormadev/vorma/vorma2/internal/tsgen/tsgencore"
)

type Opts struct {
	// Path, including filename, where the resulting TypeScript file will be written
	OutPath string

	AdHocTypes []*AdHocType

	ExtraTSCode string

	Collection            []CollectionItem
	CollectionVarName     string // Defaults to "tsgenCollection"
	ExportCollectionArray bool
}

func GenerateTSContent(opts Opts) (string, error) {
	merged := opts.to_merged()

	var collection string
	var err error
	has_coll := len(opts.Collection) > 0

	if has_coll {
		collection, err = get_coll_str(opts, merged)
		if err != nil {
			return "", err
		}
	}

	var f strings.Builder

	write(&f, Comment("Generated by tsgen. DO NOT EDIT."), 2)

	if has_coll {
		write(&f, Comment("Collection:"), 2)
		write(&f, collection, 2)
	}

	ad_hoc_types := get_exports(merged)
	if len(strings.TrimSpace(ad_hoc_types)) > 0 {
		write(&f, Comment("Ad Hoc Types:"), 2)
		write(&f, ad_hoc_types, 2)
	}

	extra_ts_trimmed := strings.TrimSpace(opts.ExtraTSCode)
	if extra_ts_trimmed != "" {
		write(&f, Comment("Extra TS Code:"), 2)
		write(&f, extra_ts_trimmed, 1)
	}

	return f.String(), nil
}

// CollectionItem represents a TypeScript object type with arbitrary properties and phantom types.
// It will be added to a constant array in the generated TypeScript file with the name
// assigned to CollectionVarName in Opts.
type CollectionItem struct {
	ArbitraryProperties map[string]any
	PhantomTypes        map[string]AdHocType
}

// Anything you'd like to add to a TypeScript type object,
// other than the phantom types. Value must be JSON-serializable.
type ArbitraryProperty struct {
	Name  string
	Value any
}

type AdHocType = tsgencore.AdHocType

type BaseOptions struct {
	CollectionVarName    string
	DiscriminatorStr     string
	CategoryPropertyName string
}

const comment_tmpl = `/////////////////////////////////////////////////////////////////////
/////// __REPLACE_ME__
/////////////////////////////////////////////////////////////////////`

func Comment(s string) string {
	return strings.Replace(comment_tmpl, "__REPLACE_ME__", s, 1)
}

func (o *Opts) to_merged() tsgencore.Results {
	var coll_cap int
	if len(o.Collection) > 0 {
		coll_cap = len(o.Collection) * len(o.Collection[0].PhantomTypes)
	}
	ad_hoc_types := make([]*AdHocType, 0, len(o.AdHocTypes)+coll_cap)

	for _, ad_hoc_type := range o.AdHocTypes {
		ad_hoc_types = append(ad_hoc_types, &AdHocType{
			TypeInstance: ad_hoc_type.TypeInstance,
			TSTypeName:   ad_hoc_type.TSTypeName,
		})
	}
	for _, item := range o.Collection {
		for _, phantom_type := range item.PhantomTypes {
			if _, isTSTypeRaw := phantom_type.TypeInstance.(TSTyperRaw); isTSTypeRaw {
				continue
			}
			ad_hoc_types = append(ad_hoc_types, &AdHocType{
				TypeInstance: phantom_type.TypeInstance,
				TSTypeName:   phantom_type.TSTypeName,
			})
		}
	}

	return tsgencore.ProcessTypes(ad_hoc_types)
}

type TSTyperRaw interface {
	TSTypeRaw() string
}

func get_coll_str(opts Opts, merged tsgencore.Results) (string, error) {
	coll := &strings.Builder{}

	if opts.ExportCollectionArray {
		write(coll, "export ")
	}
	write(coll, "const ")
	if opts.CollectionVarName == "" {
		write(coll, "tsgenCollection")
	} else {
		write(coll, opts.CollectionVarName)
	}
	write(coll, " = [", 1)

	item_strs := make([]string, 0, len(opts.Collection))

	for _, item := range opts.Collection {
		lines := make(
			[]string,
			0,
			len(
				item.ArbitraryProperties,
			)+len(
				item.PhantomTypes,
			)+len(
				item.PhantomTypes,
			),
		)

		for k, v := range item.ArbitraryProperties {
			property := &strings.Builder{}

			write(property, "\t\t")
			write(property, k)
			write(property, ": ")

			formatted_val, err := format_js_val(v)
			if err != nil {
				return "", err
			}

			write(property, formatted_val)
			write(property, ",", 1)

			lines = append(lines, property.String())
		}

		for prop_name, ad_hoc_type := range item.PhantomTypes {
			phantom_type_line := &strings.Builder{}

			write(phantom_type_line, "\t\t")
			write(phantom_type_line, prop_name)
			write(phantom_type_line, ": ")

			_, is_ts_typer_raw := ad_hoc_type.TypeInstance.(TSTyperRaw)
			if is_ts_typer_raw {
				t := reflect.TypeOf(ad_hoc_type.TypeInstance)
				if t.Kind() == reflect.Pointer {
					t = t.Elem()
				}
				x := reflect.New(t).Interface().(TSTyperRaw)
				write(phantom_type_line, "null as unknown as ")
				write(phantom_type_line, x.TSTypeRaw())
			} else {
				type_info := merged.TypeInfo(&ad_hoc_type)

				// NOTE: This assumes that your handlers are resilient
				// against return nil values. Technically, Go's JSON
				// marshalling would return "null" for nil values, and
				// the below does NOT reflect that. It assumes that
				// the type is set to its effective dereferenced (in
				// the case of pointers) and/or initialized (in the case of
				// maps or slices) "ultimate" zero value of the type.

				switch {
				case type_info == nil || type_info.IsTSNull():
					continue
				case type_info.IsTSUnknown():
					write(phantom_type_line, "null as unknown")
				case type_info.ResolvedName != "":
					write(phantom_type_line, "null as unknown as ")
					write(phantom_type_line, type_info.ResolvedName)
				case type_info.TSStr == "Record<never, never>":
					continue
				default:
					write(phantom_type_line, "null as unknown as ")
					write(phantom_type_line, type_info.TSStr)
				}
			}

			write(phantom_type_line, ",", 1)

			lines = append(lines, phantom_type_line.String())
		}

		slices.Sort(lines)

		item := &strings.Builder{}

		write(item, "\t{", 1)
		for _, line := range lines {
			write(item, line)
		}
		write(item, "\t}")

		item_strs = append(item_strs, item.String())
	}

	slices.Sort(item_strs)

	for _, item_str := range item_strs {
		coll.WriteString(item_str)
		coll.WriteString(",\n")
	}

	coll.WriteString("] as const;\n\n")

	return strings.TrimSpace(coll.String()), nil
}

func get_exports(merged tsgencore.Results) string {
	var exports_lines []string

	for _, t := range merged.Types {
		if t.ResolvedName != "" {
			sb := &strings.Builder{}
			write(sb, "export type ")
			write(sb, t.ResolvedName)
			write(sb, " = ")
			write(sb, t.TSStr)
			write(sb, ";")
			exports_lines = append(exports_lines, sb.String())
		}
	}

	slices.Sort(exports_lines)

	exports := &strings.Builder{}
	for _, line := range exports_lines {
		exports.WriteString(line)
		exports.WriteString("\n\n")
	}

	return strings.TrimSpace(exports.String())
}

func format_js_val(v any) (string, error) {
	json, err := jsonutil.Serialize(v)
	if err != nil {
		return "", err
	}
	return string(json), nil
}

func write(sb *strings.Builder, s string, returns ...int) {
	sb.WriteString(s)
	if len(returns) > 0 {
		for range returns[0] {
			sb.WriteString("\n")
		}
	}
}

type Statements [][2]string

func (m *Statements) Raw(prefix string, val string) *Statements {
	*m = append(*m, [2]string{prefix, val})
	return m
}

func (m *Statements) MustSerialize(prefix string, val any) *Statements {
	*m = append(*m, [2]string{prefix, must_serialize(val)})
	return m
}

func (m *Statements) Enum(
	const_name,
	type_name string,
	enum_struct any,
) *Statements {
	m.MustSerialize(fmt.Sprintf("export const %s", const_name), enum_struct)
	m.Raw(
		fmt.Sprintf("export type %s", type_name),
		fmt.Sprintf("(typeof %s)[keyof typeof %s]", const_name, const_name),
	)
	return m
}

func (m *Statements) BuildString() string {
	var code strings.Builder

	for _, def := range *m {
		code.WriteString(def[0])
		code.WriteString(" = ")
		code.WriteString(def[1])
		code.WriteString(";\n")
	}

	return code.String()
}

func must_serialize(v any) string {
	json, err := jsonutil.SerializePretty(v)
	if err != nil {
		panic(err)
	}

	code := string(json)

	kind := reflect.TypeOf(v).Kind()
	if kind != reflect.String && kind != reflect.Int && kind != reflect.Bool {
		code += " as const"
	}

	return code
}

func StringUnion(strs []string) string {
	if len(strs) == 0 {
		return ""
	}
	quoted := make([]string, len(strs))
	for i, s := range strs {
		quoted[i] = fmt.Sprintf("'%s'", s)
	}
	return strings.Join(quoted, " | ")
}

func TypeUnion(type_vars []string) string {
	if len(type_vars) == 0 {
		return ""
	}
	return strings.Join(type_vars, " | ")
}

// GenerateTSToFile generates a TypeScript file from the provided Opts.
func GenerateTSToFile(opts Opts) error {
	if opts.OutPath == "" {
		return errors.New("outpath is required")
	}

	ts_content, err := GenerateTSContent(opts)
	if err != nil {
		return err
	}

	err = fsutil.EnsureDir(filepath.Dir(opts.OutPath))
	if err != nil {
		return errors.New("failed to ensure out dest dir: " + err.Error())
	}

	err = os.WriteFile(opts.OutPath, []byte(ts_content), os.ModePerm)
	if err != nil {
		return errors.New("failed to write ts file: " + err.Error())
	}

	return nil
}
