/////////////////////////////////////////////////////////////////////
/////// Generated by tsgen. DO NOT EDIT.
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
/////// Collection:
/////////////////////////////////////////////////////////////////////

const routes = [
	{
		_type: "loader",
		isRootData: true,
		pattern: "/",
		phantomOutputType: null as unknown as RootData,
	},
	{
		_type: "loader",
		isSplat: true,
		pattern: "/*",
		phantomOutputType: null as unknown as DetailedPage,
	},
	{
		_type: "loader",
		params: ["dyn"],
		pattern: "/__/:dyn",
	},
	{
		_type: "loader",
		pattern: "/_index",
		phantomOutputType: null as unknown as string,
	},
] as const;

/////////////////////////////////////////////////////////////////////
/////// Ad Hoc Types:
/////////////////////////////////////////////////////////////////////

export type DetailedPage = {
	Title?: string;
	Description?: string;
	Date?: string;
	Order?: number;
	Content?: string;
	RawContent?: string;
	URL?: string;
	IsFolder?: boolean;
	Sitemap: Array<SitemapItem>;
	IndexSitemap: Array<SitemapItem>;
	BackItem: string;
};

export type RootData = {
	LatestVersion: string;
};

export type Sitemap = Array<SitemapItem>;

export type SitemapItem = {
	title: string;
	url: string;
	description?: string;
	date?: string;
	isFolder?: boolean;
	isActive?: boolean;
};

/////////////////////////////////////////////////////////////////////
/////// Extra TS Code:
/////////////////////////////////////////////////////////////////////

type VormaRootData = Extract<
	(typeof routes)[number],
	{ isRootData: true }
>["phantomOutputType"];

export type VormaApp = {
	routes: typeof routes;
	appConfig: typeof vormaAppConfig;
	rootData: VormaRootData;
};

export const vormaAppConfig = {
	actionsRouterMountRoot: "/api/",
	actionsDynamicRune: ":",
	actionsSplatRune: "*",
	loadersDynamicRune: ":",
	loadersSplatRune: "*",
	loadersExplicitIndexSegment: "_index",
	__phantom: null as unknown as VormaApp,
} as const;

import type {
	VormaLoaderPattern,
	VormaMutationInput,
	VormaMutationOutput,
	VormaMutationPattern,
	VormaMutationProps,
	VormaQueryInput,
	VormaQueryOutput,
	VormaQueryPattern,
	VormaQueryProps,
} from "vorma/client";
import type { VormaRouteProps } from "vorma/solid";

export type QueryPattern = VormaQueryPattern<VormaApp>;
export type QueryProps<P extends QueryPattern> = VormaQueryProps<VormaApp, P>;
export type QueryInput<P extends QueryPattern> = VormaQueryInput<VormaApp, P>;
export type QueryOutput<P extends QueryPattern> = VormaQueryOutput<VormaApp, P>;

export type MutationPattern = VormaMutationPattern<VormaApp>;
export type MutationProps<P extends MutationPattern> = VormaMutationProps<
	VormaApp,
	P
>;
export type MutationInput<P extends MutationPattern> = VormaMutationInput<
	VormaApp,
	P
>;
export type MutationOutput<P extends MutationPattern> = VormaMutationOutput<
	VormaApp,
	P
>;

export type RouteProps<P extends VormaLoaderPattern<VormaApp>> =
	VormaRouteProps<VormaApp, P>;

/////////////////////////////////////////////////////////////////////
/////// Vorma Vite Config:
/////////////////////////////////////////////////////////////////////

export const staticPublicAssetMap = {
	"desktop.svg": "vorma_out_desktop_eebc981612eb.svg",
	"favicon.svg": "vorma_out_favicon_d4e72b60e709.svg",
	"fonts/jetbrains_mono.woff2": "vorma_out_fonts_jetbrains_mono_1e06740a02a4.woff2",
	"fonts/jetbrains_mono_ext.woff2": "vorma_out_fonts_jetbrains_mono_ext_7db7affbce1f.woff2",
	"fonts/jetbrains_mono_italic.woff2": "vorma_out_fonts_jetbrains_mono_italic_6548575d6839.woff2",
	"fonts/jetbrains_mono_italic_ext.woff2": "vorma_out_fonts_jetbrains_mono_italic_ext_bdce8a4f00f6.woff2",
	"moon.svg": "vorma_out_moon_7e0c08985ebe.svg",
	"sun.svg": "vorma_out_sun_338b26f6045d.svg",
	"vorma-banner.webp": "vorma_out_vorma-banner_af55bc5dc9f0.webp"
} as const;

export type StaticPublicAsset = keyof typeof staticPublicAssetMap;

declare global {
	function hashedURL(
		staticPublicAsset: StaticPublicAsset,
	): string;
}

export const publicPathPrefix = "/";

export function waveRuntimeURL(
	originalPublicURL: StaticPublicAsset,
) {
	const url = staticPublicAssetMap[originalPublicURL] ?? originalPublicURL;
	return publicPathPrefix + url;
}

export const vormaViteConfig = {
	rollupInput: [
		"frontend/src/components/dyn.tsx",
		"frontend/src/components/home.tsx",
		"frontend/src/components/md.tsx",
		"frontend/src/vorma.entry.tsx"
	],
	publicPathPrefix,
	staticPublicAssetMap,
	buildtimePublicURLFuncName: "hashedURL",
	ignoredPatterns: [
		"**/*.go",
		"**/backend/dist/**/*",
		"**/backend/assets/**/*",
		"**/backend/wave.config.json",
		"**/frontend/src/vorma.gen.ts",
		"**/frontend/src/vorma.routes.ts"
	],
	dedupeList: [
		"solid-js",
		"solid-js/web"
	],
} as const;
