package vormabuild

import (
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"github.com/vormadev/vorma"
	"github.com/vormadev/vorma/internal/pkg/vormarun"
	"github.com/vormadev/vorma/kit/fsutil"
	"github.com/vormadev/vorma/kit/matcher"
	"github.com/vormadev/vorma/kit/tsgen"
)

type live_ts_result struct {
	RoutesSection        string
	CoreTypesSection     string
	BakedAppTypesSection string
	UserTSSection        string
}

type static_ts_result struct {
	PublicURLSetupSection string
}

/////////////////////////////////////////////////////////////////////
/////// RUN STATE -- WRITE TS GEN OUT FILE
/////////////////////////////////////////////////////////////////////

// Acquires lock.
func (rs *run_state) write_ts_gen_out_file() error {
	cfg, err := rs.get_config()
	if err != nil {
		return fmt.Errorf("error getting config: %w", err)
	}

	if err := fsutil.EnsureDir(filepath.Dir(cfg.ts_gen_out_file())); err != nil {
		return fmt.Errorf("error ensuring TS gen output directory: %w", err)
	}

	ts_gen_str := strings.Builder{}

	block_comment := func(s string) {
		ts_gen_str.WriteString(
			"/////////////////////////////////////////////////////////////////////\n",
		)
		fmt.Fprintf(&ts_gen_str, "/// %s\n", s)
		ts_gen_str.WriteString(
			"/////////////////////////////////////////////////////////////////////\n",
		)
	}

	// block_comment("Generated by Vorma. Do not edit.")
	ts_gen_str.WriteString("/////// Generated by Vorma. Do not edit.\n\n")
	block_comment("Routes:")
	ts_gen_str.WriteString("\n")
	ts_gen_str.WriteString(rs.live_ts_result.RoutesSection)
	ts_gen_str.WriteString("\n")
	block_comment("Core Types:")
	ts_gen_str.WriteString("\n")
	ts_gen_str.WriteString(rs.live_ts_result.CoreTypesSection)
	ts_gen_str.WriteString("\n")
	block_comment("Baked Application Types:")
	ts_gen_str.WriteString("\n")
	ts_gen_str.WriteString(rs.live_ts_result.BakedAppTypesSection)
	ts_gen_str.WriteString("\n")
	block_comment("Public URL Setup:")
	ts_gen_str.WriteString("\n")
	pub_section := rs.static_ts_result.PublicURLSetupSection
	rs.mu.Lock()
	pub_fm := rs.pub_fm
	rs.mu.Unlock()
	if pub_fm != nil {
		pub_section = render_ts_public_url_setup_section(pub_fm)
	}
	ts_gen_str.WriteString(pub_section)
	if rs.live_ts_result.UserTSSection != "" {
		ts_gen_str.WriteString("\n")
		block_comment("User Gen:")
		ts_gen_str.WriteString("\n")
		ts_gen_str.WriteString(rs.live_ts_result.UserTSSection)
		ts_gen_str.WriteString("\n")
	}

	if err := write_str_to_file(ts_gen_str.String(), cfg.ts_gen_out_file()); err != nil {
		return fmt.Errorf("error writing TS collection section to dist: %w", err)
	}

	return nil
}

/////////////////////////////////////////////////////////////////////
/////// TS GEN -- HIGH-LEVEL GEN RESULT CREATOR
/////////////////////////////////////////////////////////////////////

func (cfg vorma_cfg) to_live_ts_result(
	loaders vorma.Loaders,
	actions vorma.Actions,
	supplemental_go_types []*tsgen.GoTypeSrc,
	user_ts string,
) (live_ts_result, error) {
	registry := &tsgen.GoTypeRegistry{}

	for _, l := range loaders {
		registry.Add(l.IType(), l.OType())
	}
	for _, a := range actions {
		registry.Add(a.IType(), a.OType())
	}
	for _, t := range supplemental_go_types {
		registry.Add(t)
	}

	resolved_types, err := registry.ResolveTypes()
	if err != nil {
		return live_ts_result{}, fmt.Errorf("error resolving Go types for TS generation: %w", err)
	}

	return live_ts_result{
		RoutesSection:        render_ts_routes_section(loaders, actions, resolved_types),
		CoreTypesSection:     render_ts_core_types_section(resolved_types),
		BakedAppTypesSection: cfg.render_ts_baked_app_types_section(),
		UserTSSection:        user_ts,
	}, nil
}

func (cfg vorma_cfg) to_static_ts_result(pub_fm map[string]string) static_ts_result {
	return static_ts_result{PublicURLSetupSection: render_ts_public_url_setup_section(pub_fm)}
}

/////////////////////////////////////////////////////////////////////
/////// TS GEN -- ROUTES SECTION
/////////////////////////////////////////////////////////////////////

func render_ts_routes_section(
	loaders vorma.Loaders,
	actions vorma.Actions,
	ts_types tsgen.ResolvedTSTypes,
) string {
	to_t_rep := func(ts *tsgen.GoTypeSrc) string {
		if ts == nil {
			return ""
		}
		t_id := ts.ID()
		t := ts_types[t_id]
		t_rep := t.Name
		if t_rep == "" {
			t_rep = t.Body
		}
		return t_rep
	}

	var sb strings.Builder

	has_root_loader := false
	for _, l := range loaders {
		if l.GetPattern() == "/" {
			has_root_loader = true
			break
		}
	}

	if len(loaders) > 0 {
		sb.WriteString("const vormaLoaders = [\n")
	} else {
		sb.WriteString("const vormaLoaders = [] as const;\n")
	}
	for _, l := range loaders {
		pattern := l.GetPattern()
		segs := matcher.ParseSegments(pattern)

		var params []string
		for _, seg := range segs {
			if len(seg) > 0 && seg[0] == byte(vormarun.Dynamic_Param_Prefix) {
				params = append(params, seg[1:])
			}
		}
		is_splat := len(segs) > 0 && segs[len(segs)-1] == string(vormarun.Splat_Segment_Identifier)

		sb.WriteString("\t{\n")

		if len(params) > 0 {
			sb.WriteString("\t\tparams: [")
			for i, p := range params {
				if i > 0 {
					sb.WriteString(", ")
				}
				fmt.Fprintf(&sb, "%q", p)
			}
			sb.WriteString("],\n")
		}

		if is_splat {
			sb.WriteString("\t\tisSplat: true,\n")
		}

		var parents []string
		if pattern != "/" && has_root_loader {
			parents = append(parents, "/")
		}
		for _, candidate := range loaders {
			maybe_parent := candidate.GetPattern()
			if maybe_parent == pattern {
				continue
			}
			if strings.HasPrefix(pattern, maybe_parent+"/") {
				parents = append(parents, maybe_parent)
			}
		}
		if len(parents) > 0 {
			sb.WriteString("\t\tparents: [")
			for i, parent := range parents {
				if i > 0 {
					sb.WriteString(", ")
				}
				fmt.Fprintf(&sb, "%q", parent)
			}
			sb.WriteString("],\n")
		}

		fmt.Fprintf(&sb, "\t\tpattern: %q,\n", pattern)

		i_t_rep := to_t_rep(l.IType())
		if i_t_rep != "" {
			fmt.Fprintf(
				&sb,
				"\t\t__I: null as unknown as %s,\n",
				i_t_rep,
			)
		}

		t_rep := to_t_rep(l.OType())
		if t_rep != "" {
			fmt.Fprintf(
				&sb,
				"\t\t__O: null as unknown as %s,\n",
				t_rep,
			)
		}

		sb.WriteString("\t},\n")
	}
	if len(loaders) > 0 {
		sb.WriteString("] as const;\n")
	}

	sb.WriteString("\n")

	if len(actions) > 0 {
		sb.WriteString("const vormaActions = [\n")
	} else {
		sb.WriteString("const vormaActions = [] as const;\n")
	}
	for _, a := range actions {
		pattern, method := a.GetPattern(), a.GetMethod()

		segs := matcher.ParseSegments(pattern)

		var params []string
		for _, seg := range segs {
			if len(seg) > 0 && seg[0] == byte(vormarun.Dynamic_Param_Prefix) {
				params = append(params, seg[1:])
			}
		}

		sb.WriteString("\t{\n")
		fmt.Fprintf(&sb, "\t\tmethod: %q,\n", method)

		if len(params) > 0 {
			sb.WriteString("\t\tparams: [")
			for i, p := range params {
				if i > 0 {
					sb.WriteString(", ")
				}
				fmt.Fprintf(&sb, "%q", p)
			}
			sb.WriteString("],\n")
		}

		fmt.Fprintf(&sb, "\t\tpattern: %q,\n", pattern)

		i_t_rep := to_t_rep(a.IType())
		if i_t_rep != "" {
			fmt.Fprintf(
				&sb,
				"\t\t__I: null as unknown as %s,\n",
				i_t_rep,
			)
		}
		o_t_rep := to_t_rep(a.OType())
		if o_t_rep != "" {
			fmt.Fprintf(
				&sb,
				"\t\t__O: null as unknown as %s,\n",
				o_t_rep,
			)
		}

		sb.WriteString("\t},\n")
	}
	if len(actions) > 0 {
		sb.WriteString("] as const;\n")
	}

	return sb.String()
}

/////////////////////////////////////////////////////////////////////
/////// TS GEN -- CORE TYPES SECTION
/////////////////////////////////////////////////////////////////////

func render_ts_core_types_section(ts_types tsgen.ResolvedTSTypes) string {
	sorted_ids := make([]tsgen.ID, 0, len(ts_types))
	for id := range ts_types {
		sorted_ids = append(sorted_ids, id)
	}
	slices.SortFunc(sorted_ids, func(a, b tsgen.ID) int {
		return strings.Compare(string(a), string(b))
	})

	var sb strings.Builder
	for i, id := range sorted_ids {
		t := ts_types[id]
		if t.Name == "" {
			continue
		}
		fmt.Fprintf(&sb, "export type %s = %s;\n", t.Name, t.Body)
		if i < len(sorted_ids)-1 {
			sb.WriteString("\n")
		}
	}
	return sb.String()
}

/////////////////////////////////////////////////////////////////////
/////// TS GEN -- BAKED APP TYPES SECTION
/////////////////////////////////////////////////////////////////////

func (cfg vorma_cfg) render_ts_baked_app_types_section() string {
	sb := strings.Builder{}

	fmt.Fprintf(&sb, `import type { VormaAppConfig } from "vorma/%s";`, cfg.ui_variant())

	sb.WriteString("\n\n")

	fmt.Fprintf(&sb, `export const vormaAppConfig = {
	actionsMountRoot: "%s",
    __phantom_loaders: null as unknown as typeof vormaLoaders,
    __phantom_actions: null as unknown as typeof vormaActions,
} as const satisfies VormaAppConfig;`, cfg.actions_mount_root())

	sb.WriteString("\n\n")

	sb.WriteString(`export type App = typeof vormaAppConfig;`)

	sb.WriteString("\n")

	return sb.String()
}

/////////////////////////////////////////////////////////////////////
/////// TS GEN -- PUBLIC URL SETUP SECTION
/////////////////////////////////////////////////////////////////////

func render_ts_public_url_setup_section(pub_fm map[string]string) string {
	sb := strings.Builder{}

	sb.WriteString(`declare global {
	/** Argument must be a static string literal. */
	function vormaPublicURL(k: VormaPublicURLKey): string;
}`)

	sb.WriteString("\n\n")

	collected_pub_fm := make(map[string]string)
	collected_pub_fm_keys := make([]string, 0, len(pub_fm))
	for k, v := range pub_fm {
		if k == vormarun.Main_CSS_Filename {
			continue
		}
		collected_pub_fm[k] = v
		collected_pub_fm_keys = append(collected_pub_fm_keys, k)
	}
	slices.Sort(collected_pub_fm_keys)

	if len(collected_pub_fm_keys) == 0 {
		sb.WriteString("export type VormaPublicURLKey = never;\n")
		return sb.String()
	}

	sb.WriteString("const vormaPublicURLKeys = [\n")
	for _, k := range collected_pub_fm_keys {
		fmt.Fprintf(&sb, "\t%q,\n", k)
	}
	sb.WriteString("] as const;\n\n")
	sb.WriteString(
		"type VormaPublicURLKey = `${\"\" | \"/\"}${(typeof vormaPublicURLKeys)[number]}`;\n",
	)

	return sb.String()
}
