// Code generated by Vorma. DO NOT EDIT.

import type { VormaClientSeed } from "vorma/react";

export const vormaClientSeed = {
	apiMountRoot: "/api/",
	__vorma_views: null as unknown as typeof __vorma_views,
	__vorma_api_routes: null as unknown as typeof __vorma_api_routes,
} as const satisfies VormaClientSeed;

declare global {
	/** Argument must be a static string literal. */
	function vormaPublicUrl(k: VormaPublicUrlKey): string;
}

const vormaPublicUrlKeys = ["fonts/IoskeleyMono-400.woff2", "mark.svg"] as const;

type VormaPublicUrlKey = `${"" | "/"}${(typeof vormaPublicUrlKeys)[number]}`;

const __vorma_api_routes = [
	{
		method: "POST",
		pattern: "/notes",
		__i: null as unknown as CreateNoteInput,
		__o: null as unknown as CreateNoteOutput,
	},
	{
		method: "GET",
		pattern: "/ping",
		__i: null as unknown as undefined,
		__o: null as unknown as PingOutput,
	},
] as const;

const __vorma_views = [
	{
		pattern: "/",
		__i: null as unknown as HomeInput,
		__o: null as unknown as HomePage,
	},
	{
		params: ["note_id"],
		parents: ["/"],
		pattern: "/notes/:note_id",
		__i: null as unknown as undefined,
		__o: null as unknown as NotePage,
	},
] as const;

export type CreateNoteInput = {
	body: string;
};

export type CreateNoteOutput = {
	note: Note;
};

export type HomeInput = {
	draft?: string | null;
};

export type HomePage = {
	app_name: string;
	draft: string | null;
	mark_url: string;
	notes: Array<Note>;
};

export type Note = {
	id: number;
	body: string;
};

export type NotePage = {
	app_name: string;
	note_id: string;
	note: Note | null;
};

export type PingOutput = {
	ok: boolean;
};
