/////// Generated by Vorma. Do not edit.

/////////////////////////////////////////////////////////////////////
/// Routes:
/////////////////////////////////////////////////////////////////////

const vormaLoaders = [
	{
		pattern: "/",
		__O: null as unknown as Record<never, never>,
	},
	{
		isSplat: true,
		pattern: "/*",
		__O: null as unknown as Result,
	},
] as const;

const vormaActions = [] as const;

/////////////////////////////////////////////////////////////////////
/// Core Types:
/////////////////////////////////////////////////////////////////////

export type Page = {
	Title: string;
	Description: string;
	Date: string;
	Order: number;
	HTML: string;
	Raw: string;
	URL: string;
	IsFolder: boolean;
};

export type Result = {
	Page?: Page;
	Siblings: Array<NavItem>;
	Children: Array<NavItem>;
	ParentURL: string;
};

export type NavItem = {
	Title: string;
	URL: string;
	Description: string;
	Date: string;
	IsFolder: boolean;
	IsActive: boolean;
};

/////////////////////////////////////////////////////////////////////
/// Baked Application Types:
/////////////////////////////////////////////////////////////////////

import type { VormaAppConfig } from "vorma/solid";

export const vormaAppConfig = {
	actionsMountRoot: "/api/",
	__phantom_loaders: null as unknown as typeof vormaLoaders,
	__phantom_actions: null as unknown as typeof vormaActions,
} as const satisfies VormaAppConfig;

export type App = typeof vormaAppConfig;

/////////////////////////////////////////////////////////////////////
/// Public URL Setup:
/////////////////////////////////////////////////////////////////////

declare global {
	function vormaPublicURL(k: VormaPublicURLKey): string;
}

const vormaPublicURLKeys = [
	"fonts/IoskeleyMono-100-i.woff2",
	"fonts/IoskeleyMono-100.woff2",
	"fonts/IoskeleyMono-200-i.woff2",
	"fonts/IoskeleyMono-200.woff2",
	"fonts/IoskeleyMono-300-i.woff2",
	"fonts/IoskeleyMono-300.woff2",
	"fonts/IoskeleyMono-350-i.woff2",
	"fonts/IoskeleyMono-350.woff2",
	"fonts/IoskeleyMono-400-i.woff2",
	"fonts/IoskeleyMono-400.woff2",
	"fonts/IoskeleyMono-500-i.woff2",
	"fonts/IoskeleyMono-500.woff2",
	"fonts/IoskeleyMono-600-i.woff2",
	"fonts/IoskeleyMono-600.woff2",
	"fonts/IoskeleyMono-700-i.woff2",
	"fonts/IoskeleyMono-700.woff2",
	"fonts/IoskeleyMono-800-i.woff2",
	"fonts/IoskeleyMono-800.woff2",
	"fonts/IoskeleyMono-900-i.woff2",
	"fonts/IoskeleyMono-900.woff2",
] as const;

export type VormaPublicURLKey = (typeof vormaPublicURLKeys)[number];
