// Code generated by Vorma. DO NOT EDIT.
//
// Vite plugin contract constants and types, rendered from the Rust
// definitions in crates/vorma-build/src/vite_plugin_contract.rs (see
// crates/vorma-build/src/vite_plugin_ts_contracts.rs). Regenerate with:
//
//   VORMA_UPDATE_WIRE_CONTRACTS=1 cargo test -p vorma-build vite_plugin_ts_contracts

export const env_key = "__VORMA_VITE_PLUGIN_SERVER_PORT";
export const token_env_key = "__VORMA_VITE_PLUGIN_SERVER_TOKEN";
export const token_header = "x-vorma-vite-plugin-token";
export const loopback_host = "127.0.0.1";
export const plugin_base_path = "/vite-plugin";
export const rpc_path = "/rpc";
export const cfg_changed_path = "/cfg-changed";
export const assets_changed_path = "/assets-changed";
export const public_url_prefix = "@public/";

export type VitePluginConfig = {
	public_static_base_path: string;
	entry_module: string;
	view_modules: Array<string>;
	ignored_patterns: Array<string>;
	dedupe_list: Array<string>;
};

export type RpcRequest =
	| { method: "cfg" }
	| { method: "hash"; src_path: string }
	| { method: "set_port"; port: number };
