[package]
name = "vorma-matcher"
description = "Path pattern parsing and matching."
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
rustc-hash = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "matching"
harness = false
