// Code generated by Vorma. DO NOT EDIT.

import type { VormaClientSeed } from "vorma/remix";

export const vormaClientSeed = {
	apiMountRoot: "/api/",
	__vormaViews: null as unknown as typeof __vormaViews,
	__vormaAPIRoutes: null as unknown as typeof __vormaAPIRoutes,
} as const satisfies VormaClientSeed;

declare global {
	/** Argument must be a static string literal. */
	function vormaPublicURL(k: VormaPublicURLKey): string;
}

const vormaPublicURLKeys = [
	"favicon.svg",
	"fonts/IoskeleyMono-100-i.woff2",
	"fonts/IoskeleyMono-100.woff2",
	"fonts/IoskeleyMono-200-i.woff2",
	"fonts/IoskeleyMono-200.woff2",
	"fonts/IoskeleyMono-300-i.woff2",
	"fonts/IoskeleyMono-300.woff2",
	"fonts/IoskeleyMono-350-i.woff2",
	"fonts/IoskeleyMono-350.woff2",
	"fonts/IoskeleyMono-400-i.woff2",
	"fonts/IoskeleyMono-400.woff2",
	"fonts/IoskeleyMono-500-i.woff2",
	"fonts/IoskeleyMono-500.woff2",
	"fonts/IoskeleyMono-600-i.woff2",
	"fonts/IoskeleyMono-600.woff2",
	"fonts/IoskeleyMono-700-i.woff2",
	"fonts/IoskeleyMono-700.woff2",
	"fonts/IoskeleyMono-800-i.woff2",
	"fonts/IoskeleyMono-800.woff2",
	"fonts/IoskeleyMono-900-i.woff2",
	"fonts/IoskeleyMono-900.woff2",
	"vorma-banner.webp",
] as const;

type VormaPublicURLKey = `${"" | "/"}${(typeof vormaPublicURLKeys)[number]}`;

const __vormaAPIRoutes = [] as const;

const __vormaViews = [
	{
		pattern: "/",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as Record<never, never>,
	},
	{
		isSplat: true,
		parents: ["/"],
		pattern: "/*",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as Result,
	},
] as const;

export type Page = {
	Title: string;
	Description: string;
	Date: string;
	Order: number;
	HTML: string;
	Raw: string;
	URL: string;
	IsFolder: boolean;
};

export type Result = {
	Page?: Page;
	Siblings: Array<NavItem>;
	Children: Array<NavItem>;
	ParentURL: string;
};

export type NavItem = {
	Title: string;
	URL: string;
	Description: string;
	Date: string;
	IsFolder: boolean;
	IsActive: boolean;
};
