package vormabuild

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vormadev/vorma/kit/set"
	"github.com/vormadev/vorma/kit/strict"
	"github.com/vormadev/vorma/vorma2/internal/constants"
)

// registration_imports maps import paths to the set of function
// names that constitute a registration call when qualified with
// that package's alias.
var registration_imports = map[string]map[string]struct{}{
	"github.com/vormadev/vorma/vorma2": {
		"RegisterLoader": {},
		"RegisterAction": {},
	},
	"github.com/vormadev/vorma": {
		"RegisterLoader": {},
		"RegisterAction": {},
	},
}

var skip_dirs = map[string]struct{}{
	".git":         {},
	"node_modules": {},
	".wavedist":    {},
	"vendor":       {},
	"testdata":     {},
}

// scanned_package holds the metadata collected for one Go package
// during the module-tree walk.
type scanned_package struct {
	imports        *set.Set[string]
	is_main        bool
	calls_register bool
}

// discover_backend_packages finds all packages in the user's Go
// module that need to be blank-imported so that their init-time
// loader/action registrations execute before the build runs.
//
// The algorithm:
//  1. Walk the module tree and parse every non-test .go file with
//     full AST mode, collecting imports and package names.
//  2. For files that import a vorma registration package, walk the
//     AST for qualified calls (e.g. vorma2.RegisterLoader) to
//     identify "registration bridge" packages.
//  3. BFS the reverse import graph from the bridges to find all
//     transitive importers within the user's module.
//  4. Filter out main packages (cannot be blank-imported) and the
//     generated output package (would create a circular import).
func discover_backend_packages(
	root_dir strict.CWDRelPath,
	gen_out_dir strict.CWDRelPath,
) ([]string, error) {
	module_path, module_root, err := find_module_path(root_dir.Str())
	if err != nil {
		return nil, err
	}

	packages, err := scan_go_packages(module_root, module_path)
	if err != nil {
		return nil, err
	}

	gen_out_import := gen_output_import_path(
		gen_out_dir, module_root, module_path,
	)

	bridges := find_registration_bridges(packages)
	if len(bridges) == 0 {
		return nil, nil
	}

	reachable := transitive_importers_of(packages, bridges)

	var result []string
	for _, pkg := range reachable {
		if pkg == gen_out_import {
			continue
		}
		info, in_module := packages[pkg]
		if !in_module {
			continue
		}
		if info.is_main {
			continue
		}
		result = append(result, pkg)
	}

	sort.Strings(result)
	return result, nil
}

// gen_output_import_path computes the Go import path for the
// generated output directory. Returns "" if the directory is
// outside the module root.
func gen_output_import_path(
	gen_out_dir strict.CWDRelPath,
	module_root string,
	module_path string,
) string {
	abs, err := filepath.Abs(gen_out_dir.Str())
	if err != nil {
		return ""
	}
	rel, err := filepath.Rel(module_root, abs)
	if err != nil || strings.HasPrefix(rel, "..") {
		return ""
	}
	if rel == "." {
		return module_path
	}
	return module_path + "/" + filepath.ToSlash(rel)
}

// write_imports_gen writes a Go source file with blank imports of
// the given packages. Writes an import-less package declaration
// when import_paths is empty.
func write_imports_gen(
	output_dir strict.CWDRelPath,
	import_paths []string,
) error {
	var b strings.Builder
	b.WriteString("// Code generated by vorma2. DO NOT EDIT.\n")
	b.WriteString("package autoreg\n")
	if len(import_paths) > 0 {
		b.WriteString("\nimport (\n")
		for _, p := range import_paths {
			fmt.Fprintf(&b, "\t_ %q\n", p)
		}
		b.WriteString(")\n")
	}

	out_path := filepath.Join(
		output_dir.Str(),
		constants.GENERATED_GO_IMPORTS_FILENAME,
	)
	return os.WriteFile(out_path, []byte(b.String()), 0644)
}

// find_module_path walks up from start_dir to find go.mod and
// returns the module path and the directory containing go.mod.
func find_module_path(start_dir string) (string, string, error) {
	dir, err := filepath.Abs(start_dir)
	if err != nil {
		return "", "", err
	}
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err == nil {
			mod_path := parse_module_line(data)
			if mod_path == "" {
				return "", "", fmt.Errorf(
					"go.mod at %s has no module directive", dir,
				)
			}
			return mod_path, dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", fmt.Errorf("go.mod not found above %s", start_dir)
		}
		dir = parent
	}
}

func parse_module_line(go_mod []byte) string {
	for _, line := range strings.Split(string(go_mod), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "module ") {
			return strings.TrimSpace(trimmed[len("module "):])
		}
	}
	return ""
}

// scan_go_packages walks the module tree, parses every non-test
// .go file with full AST mode, and determines whether each package
// contains qualified registration calls.
func scan_go_packages(
	module_root string,
	module_path string,
) (map[string]*scanned_package, error) {
	packages := map[string]*scanned_package{}
	fset := token.NewFileSet()

	err := filepath.WalkDir(
		module_root,
		func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				if _, skip := skip_dirs[d.Name()]; skip {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(d.Name(), ".go") ||
				strings.HasSuffix(d.Name(), "_test.go") {
				return nil
			}

			f, parse_err := parser.ParseFile(fset, path, nil, 0)
			if parse_err != nil {
				return nil // skip unparseable files
			}

			rel, err := filepath.Rel(module_root, filepath.Dir(path))
			if err != nil {
				return nil
			}
			pkg_import_path := module_path
			if rel != "." {
				pkg_import_path = module_path + "/" +
					filepath.ToSlash(rel)
			}

			if _, exists := packages[pkg_import_path]; !exists {
				packages[pkg_import_path] = &scanned_package{
					imports: &set.Set[string]{},
				}
			}
			pkg := packages[pkg_import_path]

			if f.Name.Name == "main" {
				pkg.is_main = true
			}

			// Build a map from local alias → import path for this
			// file's imports. Also record all imports on the package.
			alias_to_import := make(map[string]string)
			for _, imp := range f.Imports {
				imp_path := strings.Trim(imp.Path.Value, `"`)
				pkg.imports.Add(imp_path)

				if _, is_reg := registration_imports[imp_path]; !is_reg {
					continue
				}

				var alias string
				if imp.Name != nil {
					alias = imp.Name.Name
				} else {
					// Default alias is the last segment of the path.
					parts := strings.Split(imp_path, "/")
					alias = parts[len(parts)-1]
				}
				if alias == "_" || alias == "." {
					continue
				}
				alias_to_import[alias] = imp_path
			}

			// If this file has no registration imports, skip the
			// AST walk.
			if len(alias_to_import) == 0 || pkg.calls_register {
				return nil
			}

			// Walk the AST looking for call expressions of the form
			// alias.RegisterLoader(...) or alias.RegisterAction(...).
			ast.Inspect(f, func(n ast.Node) bool {
				if pkg.calls_register {
					return false // already found, stop walking
				}
				call, ok := n.(*ast.CallExpr)
				if !ok {
					return true
				}
				sel, ok := call.Fun.(*ast.SelectorExpr)
				if !ok {
					return true
				}
				ident, ok := sel.X.(*ast.Ident)
				if !ok {
					return true
				}
				imp_path, alias_exists := alias_to_import[ident.Name]
				if !alias_exists {
					return true
				}
				funcs := registration_imports[imp_path]
				if _, is_reg := funcs[sel.Sel.Name]; is_reg {
					pkg.calls_register = true
					return false
				}
				return true
			})

			return nil
		},
	)
	return packages, err
}

// find_registration_bridges returns the import paths of packages
// that contain verified qualified calls to registration functions.
func find_registration_bridges(
	packages map[string]*scanned_package,
) []string {
	var bridges []string
	for pkg, info := range packages {
		if info.calls_register {
			bridges = append(bridges, pkg)
		}
	}
	sort.Strings(bridges)
	return bridges
}

// transitive_importers_of finds all packages that transitively
// import any of the target packages, via BFS over the reverse
// import graph. The targets themselves are included in the result
// when they appear in the packages map.
func transitive_importers_of(
	packages map[string]*scanned_package,
	targets []string,
) []string {
	// Build reverse graph: imported → set of importers.
	reverse := map[string]*set.Set[string]{}
	for pkg, info := range packages {
		for imp := range info.imports.Range() {
			if _, exists := reverse[imp]; !exists {
				reverse[imp] = &set.Set[string]{}
			}
			reverse[imp].Add(pkg)
		}
	}

	// BFS from every target through reverse edges.
	visited := &set.Set[string]{}
	queue := make([]string, len(targets))
	copy(queue, targets)

	for len(queue) > 0 {
		current := queue[0]
		queue = queue[1:]
		if visited.Has(current) {
			continue
		}
		visited.Add(current)
		if importers, exists := reverse[current]; exists {
			for imp := range importers.Range() {
				if !visited.Has(imp) {
					queue = append(queue, imp)
				}
			}
		}
	}

	// Collect visited packages that are in the user's module.
	var result []string
	for pkg := range visited.Range() {
		if _, in_module := packages[pkg]; in_module {
			result = append(result, pkg)
		}
	}
	sort.Strings(result)
	return result
}
