package vormabuild

import (
	"fmt"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vormadev/vorma/kit/set"
	"github.com/vormadev/vorma/kit/strict"
	"github.com/vormadev/vorma/vorma2/internal/constants"
)

// vorma2_registration_import is the import path that user code pulls
// in to register loaders and actions. Any package in the user's
// module that transitively imports this path is a registration
// package and needs a blank import in the generated file.
const vorma2_registration_import = "github.com/vormadev/vorma/vorma2"

var skip_dirs = map[string]struct{}{
	".git":         {},
	"node_modules": {},
	".waveout":     {},
	"vendor":       {},
	"testdata":     {},
}

// discover_backend_packages finds all packages in the user's Go
// module that transitively import the vorma2 registration package.
func discover_backend_packages(
	root_dir strict.CWDRelPath,
) ([]string, error) {
	module_path, module_root, err := find_module_path(root_dir.Str())
	if err != nil {
		return nil, err
	}

	packages, err := scan_go_packages(module_root, module_path)
	if err != nil {
		return nil, err
	}

	dependents := transitive_dependents(packages, vorma2_registration_import)
	sort.Strings(dependents)
	return dependents, nil
}

// write_imports_gen writes a Go source file with blank imports
// of the given packages. The file is generated output and should
// be committed alongside the generated TS files.
func write_imports_gen(
	output_dir strict.CWDRelPath,
	import_paths []string,
) error {
	var b strings.Builder
	b.WriteString("// Code generated by vorma2. DO NOT EDIT.\n")
	b.WriteString("package autoreg\n\nimport (\n")
	for _, p := range import_paths {
		fmt.Fprintf(&b, "\t_ %q\n", p)
	}
	b.WriteString(")\n")

	out_path := filepath.Join(
		output_dir.Str(),
		constants.GENERATED_GO_IMPORTS_FILENAME,
	)
	return os.WriteFile(out_path, []byte(b.String()), 0644)
}

// find_module_path walks up from start_dir to find go.mod and
// returns the module path and the directory containing go.mod.
func find_module_path(start_dir string) (string, string, error) {
	dir, err := filepath.Abs(start_dir)
	if err != nil {
		return "", "", err
	}
	for {
		data, err := os.ReadFile(filepath.Join(dir, "go.mod"))
		if err == nil {
			mod_path := parse_module_line(data)
			if mod_path == "" {
				return "", "", fmt.Errorf(
					"go.mod at %s has no module directive", dir,
				)
			}
			return mod_path, dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", "", fmt.Errorf("go.mod not found above %s", start_dir)
		}
		dir = parent
	}
}

func parse_module_line(go_mod []byte) string {
	for _, line := range strings.Split(string(go_mod), "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "module ") {
			return strings.TrimSpace(trimmed[len("module "):])
		}
	}
	return ""
}

// scan_go_packages walks the module tree, parses import statements
// from every non-test .go file, and returns a map from each
// package's import path to the set of packages it imports.
func scan_go_packages(
	module_root string,
	module_path string,
) (map[string]*set.Set[string], error) {
	packages := map[string]*set.Set[string]{}
	fset := token.NewFileSet()

	err := filepath.WalkDir(
		module_root,
		func(path string, d fs.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() {
				if _, skip := skip_dirs[d.Name()]; skip {
					return filepath.SkipDir
				}
				return nil
			}
			if !strings.HasSuffix(d.Name(), ".go") ||
				strings.HasSuffix(d.Name(), "_test.go") {
				return nil
			}

			f, parse_err := parser.ParseFile(
				fset,
				path,
				nil,
				parser.ImportsOnly,
			)
			if parse_err != nil {
				return nil // skip unparseable files
			}

			rel, err := filepath.Rel(module_root, filepath.Dir(path))
			if err != nil {
				return nil
			}
			pkg_import_path := module_path
			if rel != "." {
				pkg_import_path = module_path + "/" + filepath.ToSlash(rel)
			}

			if _, exists := packages[pkg_import_path]; !exists {
				packages[pkg_import_path] = &set.Set[string]{}
			}
			for _, imp := range f.Imports {
				packages[pkg_import_path].Add(strings.Trim(imp.Path.Value, `"`))
			}

			return nil
		},
	)
	return packages, err
}

// transitive_dependents finds all packages in the map that
// transitively import target, via BFS over the reverse import
// graph. Returns only packages present in the input map (i.e.
// packages in the user's module, not external dependencies).
func transitive_dependents(
	packages map[string]*set.Set[string],
	target string,
) []string {
	// build reverse graph: imported_path → set of importers
	reverse := map[string]*set.Set[string]{}
	for pkg, imports := range packages {
		for imp := range imports.Range() {
			if _, exists := reverse[imp]; !exists {
				reverse[imp] = &set.Set[string]{}
			}
			reverse[imp].Add(pkg)
		}
	}

	// BFS from target through reverse edges
	visited := &set.Set[string]{}
	queue := []string{target}
	for len(queue) > 0 {
		current := queue[0]
		queue = queue[1:]
		if visited.Has(current) {
			continue
		}
		visited.Add(current)
		if importers, exists := reverse[current]; exists {
			for imp := range importers.Range() {
				if !visited.Has(imp) {
					queue = append(queue, imp)
				}
			}
		}
	}

	// collect results: visited packages that are in the user's
	// module, excluding the target itself
	var result []string
	for pkg := range visited.Range() {
		if pkg == target {
			continue
		}
		if _, in_module := packages[pkg]; in_module {
			result = append(result, pkg)
		}
	}
	sort.Strings(result)
	return result
}
