// Code generated by Vorma. DO NOT EDIT.
//
// Framework wire-contract types and constants, rendered from the Rust
// definitions in crates/vorma (see crates/vorma-build/src/wire_ts_contracts.rs).
// Regenerate with:
//
//   VORMA_UPDATE_WIRE_CONTRACTS=1 cargo test -p vorma-build wire_ts_contracts

export const VORMA_JSON_KEY = "vorma-json";
export const DATA_SCRIPT_ID = "vorma-data-json";
export const BUILD_ID_HEADER = "X-Vorma-Client-Build-Id";
export const X_VORMA_BUILD_SKEW = "X-Vorma-Build-Skew";
export const X_CLIENT_REDIRECT = "X-Client-Redirect";
export const X_VORMA_RESOURCE_BODY = "x-vorma-resource-body";
export const X_ACCEPTS_CLIENT_REDIRECT = "X-Accepts-Client-Redirect";

export type HeadElement = {
	tag?: string;
	attributes_known_safe?: Record<string, string>;
	boolean_attributes?: Array<string>;
	dangerous_inner_html?: string;
};

export type ViewPayload = {
	matched_patterns?: Array<string>;
	params?: Record<string, string>;
	splat_values?: Array<string>;
	search_schemas?: Array<unknown>;
	title?: HeadElement | null;
	meta_head_els?: Array<HeadElement>;
	rest_head_els?: Array<HeadElement>;
	import_urls?: Array<string>;
	deps?: Array<string>;
	css_bundles?: Array<string>;
	views_data?: Array<unknown>;
	outermost_server_err?: string;
	outermost_server_err_idx?: number | null;
};

export type SsrPayload = ViewPayload & {
	client_build_id?: string;
	deployment_id?: string;
	is_dev?: boolean;
};
