use std::collections::BTreeMap;
use std::fmt::Write;

use serde::{Deserialize, Serialize};
use vorma::__private::core::{
	Contract, default_resource_kind, params_for_pattern, view_parents_for_patterns,
};
use vorma::__private::tsgen::{self, ResolvedTypes, TypeRef, TypeResolver};

use crate::config::VormaCfg;
use crate::utils::write_str_to_file;

#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub(crate) struct LiveTsResult {
	pub(crate) routes_section: String,
	pub(crate) core_types_section: String,
	pub(crate) baked_app_types_section: String,
	pub(crate) user_ts_section: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub(crate) struct StaticTsResult {
	pub(crate) public_url_setup_section: String,
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub(crate) struct TsGenWriteInput {
	pub(crate) live_ts_result: LiveTsResult,
	pub(crate) static_ts_result: StaticTsResult,
}

pub(crate) fn write_ts_gen_out_file(
	cfg: &VormaCfg<'_>,
	input: &TsGenWriteInput,
) -> Result<String, String> {
	let mut ts_gen_str = String::new();

	ts_gen_str.push_str("// Code generated by Vorma. DO NOT EDIT.");
	ts_gen_str.push('\n');
	ts_gen_str.push('\n');

	ts_gen_str.push_str(&input.live_ts_result.baked_app_types_section);
	ts_gen_str.push('\n');

	ts_gen_str.push_str(&input.static_ts_result.public_url_setup_section);

	ts_gen_str.push('\n');
	ts_gen_str.push_str(&input.live_ts_result.routes_section);

	if !input.live_ts_result.core_types_section.trim().is_empty() {
		ts_gen_str.push('\n');
		ts_gen_str.push_str(&input.live_ts_result.core_types_section);
	}

	if !input.live_ts_result.user_ts_section.is_empty() {
		ts_gen_str.push('\n');
		ts_gen_str.push_str(&input.live_ts_result.user_ts_section);
		ts_gen_str.push('\n');
	}

	write_str_to_file(&ts_gen_str, cfg.ts_gen_out_file())
		.map_err(|err| format!("error writing TS collection section to dist: {err}"))?;

	Ok(ts_gen_str)
}

pub(crate) fn to_live_ts_result(
	cfg: &VormaCfg<'_>,
	contract: &Contract,
) -> Result<LiveTsResult, String> {
	let resolved_types = resolve_contract_types(cfg, contract)?;
	Ok(LiveTsResult {
		routes_section: render_ts_routes_section(contract, &resolved_types),
		core_types_section: render_ts_core_types_section(&resolved_types),
		baked_app_types_section: render_ts_baked_app_types_section(cfg),
		user_ts_section: cfg.extra_ts(),
	})
}

fn resolve_contract_types(
	cfg: &VormaCfg<'_>,
	contract: &Contract,
) -> Result<ResolvedTypes, String> {
	let mut resolver = TypeResolver::default();
	for resource in contract.resources() {
		resolver.add_root(resource.input.clone());
		resolver.add_root(resource.output.clone());
	}
	for view in contract.views() {
		resolver.add_root(view.input.clone());
		resolver.add_root(view.output.clone());
	}
	resolver.add_defs(contract.type_defs().iter().cloned());
	for extra_type in cfg.extra_types() {
		resolver.add_root(extra_type.__type_ref().clone());
		resolver.add_defs(extra_type.__type_defs().iter().cloned());
	}
	resolver.resolve().map_err(|err| err.to_string())
}

pub(crate) fn render_ts_routes_section(
	contract: &Contract,
	resolved_types: &ResolvedTypes,
) -> String {
	let mut sb = String::new();
	let resources = contract.resources();
	let views = contract.views();

	if resources.is_empty() {
		sb.push_str("const __vorma_resources = [] as const;\n");
	} else {
		sb.push_str("const __vorma_resources = [\n");
	}

	for resource in resources {
		let method = &resource.method;
		sb.push_str("\t{\n");
		writeln!(&mut sb, "\t\tmethod: {},", tsgen::string_literal(method))
			.expect("writing to string should not fail");

		if let Some(kind) = resource.kind {
			let default_kind = default_resource_kind(method);
			if kind != default_kind {
				writeln!(
					&mut sb,
					"\t\tkind: {},",
					tsgen::string_literal(kind.as_str())
				)
				.expect("writing to string should not fail");
			}
		}

		push_params_field(&mut sb, &params_for_pattern(&resource.pattern));
		writeln!(
			&mut sb,
			"\t\tpattern: {},",
			tsgen::string_literal(&resource.pattern)
		)
		.expect("writing to string should not fail");
		push_type_ref_field(&mut sb, "__i", &resource.input, resolved_types);
		push_type_ref_field(&mut sb, "__o", &resource.output, resolved_types);
		sb.push_str("\t},\n");
	}

	if !resources.is_empty() {
		sb.push_str("] as const;\n");
	}

	sb.push('\n');

	if views.is_empty() {
		sb.push_str("const __vorma_views = [] as const;\n");
	} else {
		sb.push_str("const __vorma_views = [\n");
	}

	let view_patterns = views
		.iter()
		.map(|view| view.pattern.clone())
		.collect::<Vec<_>>();
	for view in views {
		sb.push_str("\t{\n");
		push_params_field(&mut sb, &params_for_pattern(&view.pattern));
		let parents = view_parents_for_patterns(&view.pattern, &view_patterns);
		push_parents_field(&mut sb, &parents);
		writeln!(
			&mut sb,
			"\t\tpattern: {},",
			tsgen::string_literal(&view.pattern)
		)
		.expect("writing to string should not fail");
		push_type_ref_field(&mut sb, "__i", &view.input, resolved_types);
		push_type_ref_field(&mut sb, "__o", &view.output, resolved_types);
		sb.push_str("\t},\n");
	}

	if !views.is_empty() {
		sb.push_str("] as const;\n");
	}

	sb
}

fn push_params_field(out: &mut String, params: &[String]) {
	if params.is_empty() {
		return;
	}

	out.push_str("\t\tparams: [");
	for (index, param) in params.iter().enumerate() {
		if index > 0 {
			out.push_str(", ");
		}
		out.push_str(&tsgen::string_literal(param));
	}
	out.push_str("],\n");
}

fn push_parents_field(out: &mut String, parents: &[String]) {
	if parents.is_empty() {
		return;
	}

	out.push_str("\t\tparents: [");
	for (index, parent) in parents.iter().enumerate() {
		if index > 0 {
			out.push_str(", ");
		}
		out.push_str(&tsgen::string_literal(parent));
	}
	out.push_str("],\n");
}

fn push_type_ref_field(
	out: &mut String,
	field: &str,
	type_ref: &TypeRef,
	resolved_types: &ResolvedTypes,
) {
	let type_rep = resolved_types.render_type_ref(type_ref);
	if type_rep.trim().is_empty() {
		return;
	}
	writeln!(out, "\t\t{field}: null as unknown as {type_rep},")
		.expect("writing to string should not fail");
}

pub(crate) fn render_ts_core_types_section(resolved_types: &ResolvedTypes) -> String {
	tsgen::render_types(resolved_types)
}

pub(crate) fn render_ts_baked_app_types_section(cfg: &VormaCfg<'_>) -> String {
	format!(
		"import type {{ VormaClientSeed }} from \"vorma/{}\";\n\nexport const vormaClientSeed = {{\n\tapiMountRoot: {},\n\t__vorma_views: null as unknown as typeof __vorma_views,\n\t__vorma_resources: null as unknown as typeof __vorma_resources,\n}} as const satisfies VormaClientSeed;\n",
		cfg.ui_variant(),
		tsgen::string_literal(&cfg.api_mount_root()),
	)
}

pub(crate) fn render_ts_public_url_setup_section(pub_fm: &BTreeMap<String, String>) -> String {
	let mut sb = String::new();

	sb.push_str(
		r#"declare global {
	/** Argument must be a static string literal. */
	function vormaPublicUrl(k: VormaPublicUrlKey): string;
}"#,
	);
	sb.push_str("\n\n");

	let mut collected_pub_fm_keys = pub_fm.keys().cloned().collect::<Vec<_>>();
	collected_pub_fm_keys.sort();

	if collected_pub_fm_keys.is_empty() {
		sb.push_str("type VormaPublicUrlKey = never;\n");
		return sb;
	}

	if collected_pub_fm_keys.len() == 1 {
		writeln!(
			&mut sb,
			"const vormaPublicUrlKeys = [{}] as const;\n",
			js_string(&collected_pub_fm_keys[0])
		)
		.expect("writing to string should not fail");
	} else {
		sb.push_str("const vormaPublicUrlKeys = [\n");
		for k in collected_pub_fm_keys {
			writeln!(&mut sb, "\t{},", js_string(&k)).expect("writing to string should not fail");
		}
		sb.push_str("] as const;\n\n");
	}

	sb.push_str(
		"type VormaPublicUrlKey = `${\"\" | \"/\"}${(typeof vormaPublicUrlKeys)[number]}`;\n",
	);
	sb
}

fn js_string(value: &str) -> String {
	serde_json::to_string(value).expect("serializing string should not fail")
}

#[cfg(test)]
mod tests {
	use std::fs;
	use std::path::PathBuf;
	use std::time::{SystemTime, UNIX_EPOCH};

	use serde::{Deserialize, Serialize};
	use vorma::__private::Config;
	use vorma::__private::core::contract_for;
	use vorma::{FrontendConfig, PathConfig, ServerConfig, TsGenConfig};

	use super::*;
	use crate::config::to_cfg;

	vorma::app!(mod ts_gen_app for ());

	#[derive(Clone, Default, Deserialize, Serialize, vorma::TsGen)]
	struct SessionInput {
		email: String,
	}

	#[derive(Clone, Deserialize, Serialize, vorma::TsGen)]
	struct SessionOutput {
		token: String,
	}

	#[derive(Clone, Deserialize, Serialize, vorma::TsGen)]
	struct RoundTrip {
		#[serde(default)]
		name: String,
	}

	#[derive(Clone, Serialize, vorma::TsGen)]
	struct SupplementalType {
		ok: bool,
	}

	pub const USER_API: ts_gen_app::Resource = ts_gen_app::resource! {
		method: vorma::HttpMethod::GET;
		pattern: "/users/:userID";
		input: ();
		output: ();
		handler: |_| {
			Ok(())
		};
	};

	pub const SESSION_API: ts_gen_app::Resource = ts_gen_app::resource! {
		kind: vorma::ResourceKind::Query;
		method: vorma::HttpMethod::POST;
		pattern: "/sessions";
		input: SessionInput;
		output: SessionOutput;
		handler: |_| {
			Ok(SessionOutput {
				token: "token".to_owned(),
			})
		};
	};

	pub const PATCH_USER_API: ts_gen_app::Resource = ts_gen_app::resource! {
		method: vorma::HttpMethod::PATCH;
		pattern: "/users/:userID";
		input: ();
		output: ();
		handler: |_| {
			Ok(())
		};
	};

	pub const ROOT_VIEW: ts_gen_app::View = ts_gen_app::view! {
		client_file: "root.tsx";
		pattern: "/";
		input: ();
		output: ();
		handler: |_| {
			Ok(())
		};
	};

	pub const USER_VIEW: ts_gen_app::View = ts_gen_app::view! {
		client_file: "user.tsx";
		pattern: "/users/:userID/*";
		input: ();
		output: ();
		handler: |_| {
			Ok(())
		};
	};

	pub const SESSION_POST_API: ts_gen_app::Resource = ts_gen_app::resource! {
		method: vorma::HttpMethod::POST;
		pattern: "/sessions";
		input: SessionInput;
		output: SessionOutput;
		handler: |_| {
			Ok(SessionOutput {
				token: "token".to_owned(),
			})
		};
	};

	pub const ROUND_TRIP_API: ts_gen_app::Resource = ts_gen_app::resource! {
		method: vorma::HttpMethod::POST;
		pattern: "/round-trip";
		input: RoundTrip;
		output: RoundTrip;
		handler: |_| {
			Ok(RoundTrip {
				name: "name".to_owned(),
			})
		};
	};

	#[test]
	fn render_ts_baked_app_types_section_uses_snake_manifest_keys() {
		let config = Config {
			root_dir: crate::test_support::root_dir(),
			server_config: server_config(),
			path_config: PathConfig {
				public_static_base: String::new(),
				api_base: "api".to_owned(),
			},
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			ts_gen_config: crate::test_support::ts_gen_config(),
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();

		let got = render_ts_baked_app_types_section(&cfg);

		assert_eq!(
			got,
			"import type { VormaClientSeed } from \"vorma/react\";\n\nexport const vormaClientSeed = {\n\tapiMountRoot: \"/api/\",\n\t__vorma_views: null as unknown as typeof __vorma_views,\n\t__vorma_resources: null as unknown as typeof __vorma_resources,\n} as const satisfies VormaClientSeed;\n"
		);
	}

	#[test]
	fn render_ts_baked_app_types_section_uses_ts_literal_for_api_mount_root() {
		let config = Config {
			root_dir: crate::test_support::root_dir(),
			server_config: server_config(),
			path_config: PathConfig {
				public_static_base: String::new(),
				api_base: "api/\"quoted".to_owned(),
			},
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			ts_gen_config: crate::test_support::ts_gen_config(),
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();

		let got = render_ts_baked_app_types_section(&cfg);

		assert!(got.contains(r#"apiMountRoot: "/api/\"quoted/","#));
	}

	#[test]
	fn render_ts_public_url_setup_section_sorts_keys_and_preserves_literal_type_shape() {
		let got = render_ts_public_url_setup_section(&BTreeMap::from([
			("img/logo.svg".to_owned(), "/static/logo.svg".to_owned()),
			("app.css".to_owned(), "/static/app.css".to_owned()),
		]));

		assert_eq!(
			got,
			"declare global {\n\t/** Argument must be a static string literal. */\n\tfunction vormaPublicUrl(k: VormaPublicUrlKey): string;\n}\n\nconst vormaPublicUrlKeys = [\n\t\"app.css\",\n\t\"img/logo.svg\",\n] as const;\n\ntype VormaPublicUrlKey = `${\"\" | \"/\"}${(typeof vormaPublicUrlKeys)[number]}`;\n"
		);
	}

	#[test]
	fn render_ts_public_url_setup_section_uses_never_for_empty_public_map() {
		let got = render_ts_public_url_setup_section(&BTreeMap::new());

		assert_eq!(
			got,
			"declare global {\n\t/** Argument must be a static string literal. */\n\tfunction vormaPublicUrl(k: VormaPublicUrlKey): string;\n}\n\ntype VormaPublicUrlKey = never;\n"
		);
	}

	#[test]
	fn render_ts_routes_section_uses_private_resource_and_view_tables() {
		let resources = ts_gen_app::resources![USER_API, SESSION_API, PATCH_USER_API];
		let views = ts_gen_app::views![ROOT_VIEW, USER_VIEW];

		let contract = contract_for(&views, &resources).unwrap();
		let config = Config {
			root_dir: crate::test_support::root_dir(),
			server_config: server_config(),
			path_config: crate::test_support::path_config(),
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			ts_gen_config: crate::test_support::ts_gen_config(),
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();
		let resolved_types = resolve_contract_types(&cfg, &contract).unwrap();
		let got = render_ts_routes_section(&contract, &resolved_types);

		assert_eq!(
			got,
			"const __vorma_resources = [\n\
\t{\n\
\t\tmethod: \"GET\",\n\
\t\tparams: [\"userID\"],\n\
\t\tpattern: \"/users/:userID\",\n\
\t\t__i: null as unknown as undefined,\n\
\t\t__o: null as unknown as undefined,\n\
\t},\n\
\t{\n\
\t\tmethod: \"POST\",\n\
\t\tkind: \"query\",\n\
\t\tpattern: \"/sessions\",\n\
\t\t__i: null as unknown as SessionInput,\n\
\t\t__o: null as unknown as SessionOutput,\n\
\t},\n\
\t{\n\
\t\tmethod: \"PATCH\",\n\
\t\tparams: [\"userID\"],\n\
\t\tpattern: \"/users/:userID\",\n\
\t\t__i: null as unknown as undefined,\n\
\t\t__o: null as unknown as undefined,\n\
\t},\n\
] as const;\n\
\n\
const __vorma_views = [\n\
\t{\n\
\t\tpattern: \"/\",\n\
\t\t__i: null as unknown as undefined,\n\
\t\t__o: null as unknown as undefined,\n\
\t},\n\
\t{\n\
\t\tparams: [\"userID\"],\n\
\t\tparents: [\"/\"],\n\
\t\tpattern: \"/users/:userID/*\",\n\
\t\t__i: null as unknown as undefined,\n\
\t\t__o: null as unknown as undefined,\n\
\t},\n\
] as const;\n"
		);
	}

	#[test]
	fn to_live_ts_result_renders_core_type_declarations() {
		let config = Config {
			root_dir: crate::test_support::root_dir(),
			server_config: server_config(),
			path_config: crate::test_support::path_config(),
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			ts_gen_config: crate::test_support::ts_gen_config(),
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();
		let resources = ts_gen_app::resources![SESSION_POST_API];
		let views = ts_gen_app::views![];
		let contract = contract_for(&views, &resources).unwrap();

		let got = to_live_ts_result(&cfg, &contract).unwrap();

		assert!(
			got.routes_section
				.contains("__i: null as unknown as SessionInput,")
		);
		assert!(
			got.routes_section
				.contains("__o: null as unknown as SessionOutput,")
		);
		assert_eq!(
			got.core_types_section,
			"export type SessionInput = {\n\temail: string;\n};\n\nexport type SessionOutput = {\n\ttoken: string;\n};\n"
		);
	}

	#[test]
	fn to_live_ts_result_preserves_structured_extra_ts() {
		let mut extra_ts = vorma::TsDrafter::new();
		extra_ts.export_type("Extra", "{ ok: true }").unwrap();
		extra_ts
			.export_const("EXTRA_FLAGS", serde_json::json!({ "ok": true }))
			.unwrap();
		let config = Config {
			root_dir: crate::test_support::root_dir(),
			server_config: server_config(),
			path_config: crate::test_support::path_config(),
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			ts_gen_config: TsGenConfig {
				extra_ts,
				..crate::test_support::ts_gen_config()
			},
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();
		let contract = Contract::default();

		let got = to_live_ts_result(&cfg, &contract).unwrap();

		assert_eq!(
			got.user_ts_section,
			"export type Extra = { ok: true };\n\nexport const EXTRA_FLAGS = {\n  \"ok\": true\n} as const;"
		);
	}

	#[test]
	fn to_live_ts_result_includes_supplemental_extra_types() {
		let config = Config {
			root_dir: crate::test_support::root_dir(),
			server_config: server_config(),
			path_config: crate::test_support::path_config(),
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			ts_gen_config: TsGenConfig {
				extra_types: vec![vorma::TsExtraType::of::<SupplementalType>().unwrap()],
				..crate::test_support::ts_gen_config()
			},
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();
		let contract = Contract::default();

		let got = to_live_ts_result(&cfg, &contract).unwrap();

		assert_eq!(
			got.core_types_section,
			"export type SupplementalType = {\n\tok: boolean;\n};\n"
		);
	}

	#[test]
	fn to_live_ts_result_keeps_distinct_deserialize_and_serialize_type_shapes() {
		let config = Config {
			root_dir: crate::test_support::root_dir(),
			server_config: server_config(),
			path_config: crate::test_support::path_config(),
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			ts_gen_config: crate::test_support::ts_gen_config(),
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();
		let resources = ts_gen_app::resources![ROUND_TRIP_API];
		let views = ts_gen_app::views![];
		let contract = contract_for(&views, &resources).unwrap();

		let got = to_live_ts_result(&cfg, &contract).unwrap();

		assert!(
			got.routes_section
				.contains("__i: null as unknown as RoundTrip,")
		);
		assert!(
			got.routes_section
				.contains("__o: null as unknown as RoundTrip_2,")
		);
		assert_eq!(
			got.core_types_section,
			"export type RoundTrip = {\n\tname?: string;\n};\n\nexport type RoundTrip_2 = {\n\tname: string;\n};\n"
		);
	}

	#[test]
	fn write_ts_gen_out_file_assembles_sections_in_contract_order() {
		let dir = temp_dir("write-ts");
		fs::create_dir_all(&dir).unwrap();
		let out_file = dir.join("vorma.gen.ts");
		let config = Config {
			root_dir: dir.clone(),
			server_config: server_config(),
			path_config: crate::test_support::path_config(),
			ts_gen_config: TsGenConfig {
				out_file: out_file.to_string_lossy().into_owned(),
				..crate::test_support::ts_gen_config()
			},
			frontend_config: FrontendConfig {
				ui_variant: "react".to_owned(),
				..crate::test_support::frontend_config()
			},
			..Config::default()
		};
		let cfg = to_cfg(&config).unwrap();
		let input = TsGenWriteInput {
			live_ts_result: LiveTsResult {
				baked_app_types_section: "BAKED".to_owned(),
				routes_section: "ROUTES".to_owned(),
				core_types_section: "CORE".to_owned(),
				user_ts_section: "USER".to_owned(),
			},
			static_ts_result: StaticTsResult {
				public_url_setup_section: "STATIC-PUB".to_owned(),
			},
		};

		let got = write_ts_gen_out_file(&cfg, &input).unwrap();

		assert_eq!(fs::read_to_string(out_file).unwrap(), got);
		assert!(got.starts_with("// Code generated by Vorma. DO NOT EDIT.\n\nBAKED\n"));
		assert!(got.contains("STATIC-PUB"));
		assert!(got.contains("\nROUTES\nCORE\nUSER\n"));

		fs::remove_dir_all(dir).unwrap();
	}

	fn temp_dir(name: &str) -> PathBuf {
		let nonce = SystemTime::now()
			.duration_since(UNIX_EPOCH)
			.unwrap()
			.as_nanos();
		std::env::temp_dir().join(format!("vorma-ts-gen-{name}-{nonce}"))
	}

	fn server_config() -> ServerConfig {
		ServerConfig {
			cargo_package: "example-app".to_owned(),
			cargo_bin: "example-server".to_owned(),
		}
	}
}
