//! Generated TypeScript contract rendering.
//!
//! [`render_typescript_contracts`] is where the framework's bundle-size
//! contract is enforced in generated code: [`PRIVATE_VIEW_CONTRACTS_IDENTIFIER`]
//! and [`PRIVATE_RESOURCE_CONTRACTS_IDENTIFIER`] are typed via `null as
//! unknown as typeof <identifier>` rather than assigned the real
//! view/resource declaration arrays, so the generated client seed carries
//! their TYPE shape at compile time without ever importing the arrays'
//! VALUES into a browser bundle. This is why a resource's explicit
//! generated-client [`crate::projection_compiler::ResourceContract::kind_override`]
//! has to be applied by hand per API call rather than looked up from the
//! generated declaration at runtime — see that method's docs.

use std::collections::BTreeMap;
use std::fmt::Write;

use vorma_contract::constants::{BLOB_TYPE_NAME, FORM_DATA_TYPE_NAME};
use vorma_contract::contracts::{FieldDef, RawTsPart, TypeDef, TypeRefContract};

use crate::projection_compiler::{ProjectionBundle, ResourceContract, ViewPayloadContract};

/// Public generated client seed identifier: the one exported `const` every
/// generated contracts file emits, typed but not runtime-populated (see the
/// module docs above).
pub const CLIENT_SEED_IDENTIFIER: &str = "vormaClientSeed";
/// Private generated resource contract table identifier: type-only, never
/// exported and never assigned a real value (see the module docs above).
pub const PRIVATE_RESOURCE_CONTRACTS_IDENTIFIER: &str = "__vorma_resources";
/// Private generated view contract table identifier: type-only, never
/// exported and never assigned a real value (see the module docs above).
pub const PRIVATE_VIEW_CONTRACTS_IDENTIFIER: &str = "__vorma_views";
/// Public generated resource contract type name.
#[cfg(test)]
pub const RESOURCE_CONTRACTS_TYPE_NAME: &str = "VormaResourceContracts";
/// Public generated view contract type name.
#[cfg(test)]
pub const VIEW_CONTRACTS_TYPE_NAME: &str = "VormaViewContracts";

const GENERATED_HEADER: &str = "// Code generated by Vorma. DO NOT EDIT.\n\n";
const VORMA_CLIENT_SEED_TYPE_NAME: &str = "VormaClientSeed";
const PUBLIC_URL_FUNCTION_IDENTIFIER: &str = "vormaPublicUrl";
const PUBLIC_URL_KEY_TYPE_NAME: &str = "VormaPublicUrlKey";

/// Rendered generated TypeScript contracts: the complete file source text
/// [`render_typescript_contracts`] produces, ready to write to the app's
/// configured generated TypeScript output path (see
/// [`crate::build_output::write_typescript_contracts`]).
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GeneratedTypeScriptContracts {
	source: String,
}

impl GeneratedTypeScriptContracts {
	/// Generated TypeScript source.
	pub fn source(&self) -> &str {
		&self.source
	}
}

/// Render generated TypeScript contracts from compiled graph projections:
/// the type-only client seed, the public-URL literal-type setup, every
/// resource and view contract, every declared type definition (sorted by
/// export name so reordering declarations in app config does not churn the
/// generated diff), and any raw supplemental TypeScript the app registered.
pub fn render_typescript_contracts(
	bundle: &ProjectionBundle,
	public_filemap: &BTreeMap<String, String>,
) -> Result<GeneratedTypeScriptContracts, TypeScriptContractError> {
	let mut source = String::new();
	source.push_str(GENERATED_HEADER);
	render_client_seed(bundle, &mut source);
	source.push('\n');
	render_public_url_setup_section(public_filemap, &mut source);
	source.push('\n');
	render_resource_contracts(bundle.resource_contracts(), &mut source)?;
	source.push('\n');
	render_view_contracts(bundle.view_payloads(), &mut source)?;
	source.push('\n');
	for type_def in sorted_type_defs(bundle.type_defs()) {
		render_type_def(type_def, &mut source)?;
		source.push('\n');
	}
	if !bundle.generated_typescript_extra_source().is_empty() {
		source.push_str(bundle.generated_typescript_extra_source());
		source.push('\n');
	}
	normalize_trailing_newlines(&mut source);
	Ok(GeneratedTypeScriptContracts { source })
}

/// Type definitions ordered by export name, so generated output does not
/// churn when declarations are reordered in application config.
pub(crate) fn sorted_type_defs(type_defs: &[TypeDef]) -> Vec<&TypeDef> {
	let mut sorted = type_defs.iter().collect::<Vec<_>>();
	sorted.sort_by_key(|type_def| type_def.name());
	sorted
}

/// Collapse the end of a generated file to exactly one trailing newline.
pub(crate) fn normalize_trailing_newlines(source: &mut String) {
	while source.ends_with("\n\n") {
		source.pop();
	}
	if !source.ends_with('\n') {
		source.push('\n');
	}
}

/// Error from [`render_typescript_contracts`].
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum TypeScriptContractError {
	/// A type definition name was invalid.
	InvalidTypeName {
		/// Rejected type name.
		name: String,
	},
	/// A named type reference name was invalid.
	InvalidTypeReferenceName {
		/// Rejected type reference name.
		name: String,
	},
}

impl std::fmt::Display for TypeScriptContractError {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			Self::InvalidTypeName { name } => write!(f, "invalid TypeScript type name {name:?}"),
			Self::InvalidTypeReferenceName { name } => {
				write!(f, "invalid TypeScript type reference name {name:?}")
			}
		}
	}
}

impl std::error::Error for TypeScriptContractError {}

fn render_client_seed(bundle: &ProjectionBundle, source: &mut String) {
	source.push_str("import type { ");
	source.push_str(VORMA_CLIENT_SEED_TYPE_NAME);
	source.push_str(" } from ");
	source.push_str(&quoted(&ui_variant_type_module(bundle.ui_variant())));
	source.push_str(";\n\n");
	source.push_str("export const ");
	source.push_str(CLIENT_SEED_IDENTIFIER);
	source.push_str(" = {\n\t");
	source.push_str(PRIVATE_VIEW_CONTRACTS_IDENTIFIER);
	source.push_str(": null as unknown as typeof ");
	source.push_str(PRIVATE_VIEW_CONTRACTS_IDENTIFIER);
	source.push_str(",\n\t");
	source.push_str(PRIVATE_RESOURCE_CONTRACTS_IDENTIFIER);
	source.push_str(": null as unknown as typeof ");
	source.push_str(PRIVATE_RESOURCE_CONTRACTS_IDENTIFIER);
	source.push_str(",\n} as const satisfies ");
	source.push_str(VORMA_CLIENT_SEED_TYPE_NAME);
	source.push_str(";\n");
}

fn ui_variant_type_module(ui_variant: &str) -> String {
	if ui_variant.is_empty() {
		return "vorma/react".to_owned();
	}
	format!("vorma/{ui_variant}")
}

fn render_public_url_setup_section(public_filemap: &BTreeMap<String, String>, source: &mut String) {
	source.push_str("declare global {\n");
	source.push_str("\t/** Argument must be a static string literal. */\n");
	source.push('\t');
	source.push_str("function ");
	source.push_str(PUBLIC_URL_FUNCTION_IDENTIFIER);
	source.push_str("(k: ");
	source.push_str(PUBLIC_URL_KEY_TYPE_NAME);
	source.push_str("): string;\n");
	source.push_str("}\n\n");

	let public_url_keys = public_filemap.keys().cloned().collect::<Vec<_>>();
	if public_url_keys.is_empty() {
		source.push_str("type ");
		source.push_str(PUBLIC_URL_KEY_TYPE_NAME);
		source.push_str(" = never;\n");
		return;
	}
	if public_url_keys.len() == 1 {
		source.push_str("const vormaPublicUrlKeys = [");
		source.push_str(&quoted(&public_url_keys[0]));
		source.push_str("] as const;\n\n");
	} else {
		source.push_str("const vormaPublicUrlKeys = [\n");
		for public_url_key in public_url_keys {
			source.push('\t');
			source.push_str(&quoted(&public_url_key));
			source.push_str(",\n");
		}
		source.push_str("] as const;\n\n");
	}
	source.push_str("type ");
	source.push_str(PUBLIC_URL_KEY_TYPE_NAME);
	source.push_str(" = `${\"\" | \"/\"}${(typeof vormaPublicUrlKeys)[number]}`;\n");
}

pub(crate) fn render_type_def(
	type_def: &TypeDef,
	source: &mut String,
) -> Result<(), TypeScriptContractError> {
	match type_def {
		TypeDef::Alias { name, target, .. } => {
			validate_type_name(name)?;
			source.push_str("export type ");
			source.push_str(name);
			source.push_str(" = ");
			source.push_str(&render_type_ref(target)?);
			source.push_str(";\n");
		}
		TypeDef::Record { name, fields, .. } => {
			validate_type_name(name)?;
			source.push_str("export type ");
			source.push_str(name);
			source.push_str(" = ");
			if fields.is_empty() {
				source.push_str("Record<never, never>");
			} else {
				source.push_str("{\n");
				for field in fields {
					render_field_def(field, source)?;
				}
				source.push('}');
			}
			source.push_str(";\n");
		}
		TypeDef::StringEnum { name, variants, .. } => {
			validate_type_name(name)?;
			source.push_str("export type ");
			source.push_str(name);
			source.push_str(" = ");
			render_string_literal_union(variants, source);
			source.push_str(";\n");
		}
		TypeDef::Raw { name, body, .. } => {
			validate_type_name(name)?;
			source.push_str("export type ");
			source.push_str(name);
			source.push_str(" = ");
			render_raw_type_parts(body, source)?;
			source.push_str(";\n");
		}
	}
	Ok(())
}

fn render_field_def(field: &FieldDef, source: &mut String) -> Result<(), TypeScriptContractError> {
	source.push('\t');
	source.push_str(&render_property_name(field.name()));
	if field.is_optional() {
		source.push('?');
	}
	source.push_str(": ");
	source.push_str(&render_type_ref(field.type_ref())?);
	source.push_str(";\n");
	Ok(())
}

fn render_view_contracts(
	views: &[ViewPayloadContract],
	source: &mut String,
) -> Result<(), TypeScriptContractError> {
	if views.is_empty() {
		source.push_str("const ");
		source.push_str(PRIVATE_VIEW_CONTRACTS_IDENTIFIER);
		source.push_str(" = [] as const;\n");
		return Ok(());
	}
	source.push_str("const ");
	source.push_str(PRIVATE_VIEW_CONTRACTS_IDENTIFIER);
	source.push_str(" = [\n");
	for view in views {
		source.push_str("\t{\n");
		push_string_array_field(source, "params", view.params());
		push_string_array_field(source, "parents", view.parent_patterns());
		writeln!(source, "\t\tpattern: {},", quoted(view.pattern()))
			.expect("writing to string should not fail");
		push_type_ref_field(source, "__i", view.type_contract().input())?;
		push_type_ref_field(source, "__o", view.type_contract().output())?;
		source.push_str("\t},\n");
	}
	source.push_str("] as const;\n");
	Ok(())
}

fn render_resource_contracts(
	resources: &[ResourceContract],
	source: &mut String,
) -> Result<(), TypeScriptContractError> {
	if resources.is_empty() {
		source.push_str("const ");
		source.push_str(PRIVATE_RESOURCE_CONTRACTS_IDENTIFIER);
		source.push_str(" = [] as const;\n");
		return Ok(());
	}
	source.push_str("const ");
	source.push_str(PRIVATE_RESOURCE_CONTRACTS_IDENTIFIER);
	source.push_str(" = [\n");
	for resource in resources {
		source.push_str("\t{\n");
		writeln!(source, "\t\tmethod: {},", quoted(resource.method()))
			.expect("writing to string should not fail");
		if let Some(kind) = resource.kind_override()
			&& kind != resource.default_kind()
		{
			writeln!(source, "\t\tkind: {},", quoted(kind.as_str()))
				.expect("writing to string should not fail");
		}
		push_string_array_field(source, "params", resource.params());
		writeln!(source, "\t\tpattern: {},", quoted(resource.pattern()))
			.expect("writing to string should not fail");
		push_type_ref_field(source, "__i", resource.type_contract().input())?;
		push_type_ref_field(source, "__o", resource.type_contract().output())?;
		source.push_str("\t},\n");
	}
	source.push_str("] as const;\n");
	Ok(())
}

fn push_string_array_field(source: &mut String, field: &str, values: &[String]) {
	if values.is_empty() {
		return;
	}
	source.push('\t');
	source.push('\t');
	source.push_str(field);
	source.push_str(": [");
	for (index, value) in values.iter().enumerate() {
		if index > 0 {
			source.push_str(", ");
		}
		source.push_str(&quoted(value));
	}
	source.push_str("],\n");
}

fn push_type_ref_field(
	source: &mut String,
	field: &str,
	type_ref: &TypeRefContract,
) -> Result<(), TypeScriptContractError> {
	let rendered = render_type_ref(type_ref)?;
	if rendered.trim().is_empty() {
		return Ok(());
	}
	writeln!(source, "\t\t{field}: null as unknown as {rendered},")
		.expect("writing to string should not fail");
	Ok(())
}

fn render_type_ref(type_ref: &TypeRefContract) -> Result<String, TypeScriptContractError> {
	match type_ref {
		TypeRefContract::Unit => Ok("undefined".to_owned()),
		TypeRefContract::Null => Ok("null".to_owned()),
		TypeRefContract::Unknown => Ok("unknown".to_owned()),
		TypeRefContract::Bool => Ok("boolean".to_owned()),
		TypeRefContract::String => Ok("string".to_owned()),
		TypeRefContract::Number | TypeRefContract::Integer => Ok("number".to_owned()),
		TypeRefContract::Named { name, .. } => {
			if !valid_type_identifier(name) {
				return Err(TypeScriptContractError::InvalidTypeReferenceName {
					name: name.clone(),
				});
			}
			Ok(name.clone())
		}
		TypeRefContract::Array(element) => Ok(format!("Array<{}>", render_type_ref(element)?)),
		TypeRefContract::Map(key, value) => Ok(format!(
			"Record<{}, {}>",
			render_type_ref(key)?,
			render_type_ref(value)?
		)),
		TypeRefContract::FormData => Ok(FORM_DATA_TYPE_NAME.to_owned()),
		TypeRefContract::Blob => Ok(BLOB_TYPE_NAME.to_owned()),
		TypeRefContract::Nullable(inner) => Ok(format!("{} | null", render_type_ref(inner)?)),
		TypeRefContract::Union(types) => {
			if types.is_empty() {
				return Ok("never".to_owned());
			}
			let rendered = types
				.iter()
				.map(render_type_ref)
				.collect::<Result<Vec<_>, _>>()?;
			Ok(rendered.join(" | "))
		}
		TypeRefContract::StringLiteral(value) => Ok(quoted(value)),
		TypeRefContract::Raw(parts) => {
			let mut source = String::new();
			render_raw_type_parts(parts, &mut source)?;
			Ok(source)
		}
	}
}

fn render_raw_type_parts(
	parts: &[RawTsPart],
	source: &mut String,
) -> Result<(), TypeScriptContractError> {
	for part in parts {
		match part {
			RawTsPart::Text(text) => source.push_str(text),
			RawTsPart::TypeRef(type_ref) => source.push_str(&render_type_ref(type_ref)?),
		}
	}
	Ok(())
}

fn render_string_literal_union(variants: &[String], source: &mut String) {
	if variants.is_empty() {
		source.push_str("never");
		return;
	}
	for (index, variant) in variants.iter().enumerate() {
		if index > 0 {
			source.push_str(" | ");
		}
		source.push_str(&quoted(variant));
	}
}

fn render_property_name(name: &str) -> String {
	if valid_property_identifier(name) {
		return name.to_owned();
	}
	quoted(name)
}

fn validate_type_name(name: &str) -> Result<(), TypeScriptContractError> {
	if !valid_type_identifier(name) {
		return Err(TypeScriptContractError::InvalidTypeName {
			name: name.to_owned(),
		});
	}
	Ok(())
}

fn valid_type_identifier(name: &str) -> bool {
	let mut chars = name.chars();
	match chars.next() {
		Some(ch) if ch == '_' || ch == '$' || ch.is_ascii_alphabetic() => {}
		_ => return false,
	}
	chars.all(|ch| ch == '_' || ch == '$' || ch.is_ascii_alphanumeric())
}

fn valid_property_identifier(name: &str) -> bool {
	valid_type_identifier(name)
}

fn quoted(value: &str) -> String {
	serde_json::to_string(value).expect("serializing a string literal should not fail")
}

#[cfg(test)]
mod tests {
	use std::collections::BTreeMap;

	use http::Method;
	use vorma_contract::contracts::{
		DocumentContract, FieldDef, RouteTypeContract, TypeDef, TypeRefContract,
	};
	use vorma_contract::framework_graph::{
		BuildInputConfig, DevWatchConfig, FrameworkConfig, FrameworkDeclarations, FrameworkGraph,
		FrontendBuildInputs, GraphError, HandlerId, ResourceDeclaration, ServerBuildTarget,
		StaticAssetDeclaration, ViewDeclaration,
	};

	use super::*;

	fn handler_id(value: &str) -> HandlerId {
		HandlerId::new(value).unwrap()
	}

	fn named_type(key: &str, name: &str) -> TypeRefContract {
		TypeRefContract::Named {
			key: key.to_owned(),
			name: name.to_owned(),
		}
	}

	fn graph() -> FrameworkGraph {
		let mut declarations = FrameworkDeclarations::default();
		declarations.set_document(DocumentContract::default());
		declarations.add_type_def(TypeDef::Record {
			key: "User".to_owned(),
			name: "User".to_owned(),
			fields: vec![FieldDef::new("full-name", TypeRefContract::String, false)],
		});
		declarations.add_type_def(TypeDef::Record {
			key: "UserInput".to_owned(),
			name: "UserInput".to_owned(),
			fields: vec![FieldDef::new("name", TypeRefContract::String, false)],
		});
		declarations.add_view(ViewDeclaration::new(
			"/users/:id",
			"user.tsx",
			serde_json::json!({"q": "string"}),
			RouteTypeContract::new(TypeRefContract::Unit, named_type("User", "User")),
			handler_id("view"),
		));
		declarations.add_resource(ResourceDeclaration::new(
			Method::POST,
			"/users",
			None,
			Some(serde_json::json!({"body": {"name": "string"}})),
			RouteTypeContract::new(
				named_type("UserInput", "UserInput"),
				named_type("User", "User"),
			),
			handler_id("resource"),
		));
		declarations.add_static_asset(StaticAssetDeclaration::new(
			"app.css",
			"/static/app.hash.css",
		));
		FrameworkGraph::compile(declarations).unwrap()
	}

	fn public_filemap() -> BTreeMap<String, String> {
		BTreeMap::from([("app.css".to_owned(), "/static/app.hash.css".to_owned())])
	}

	#[test]
	fn generated_contracts_render_public_generated_file_shape() {
		let bundle = ProjectionBundle::compile(&graph());

		let generated = render_typescript_contracts(&bundle, &public_filemap()).unwrap();
		let source = generated.source();

		assert!(source.starts_with(
			"// Code generated by Vorma. DO NOT EDIT.\n\nimport type { VormaClientSeed } from \"vorma/react\";"
		));
		assert!(source.contains(&format!("export const {CLIENT_SEED_IDENTIFIER} = {{")));
		assert!(source.contains("const vormaPublicUrlKeys = [\"app.css\"] as const;"));
		assert!(source.contains(&format!(
			"const {PRIVATE_RESOURCE_CONTRACTS_IDENTIFIER} = ["
		)));
		assert!(source.contains("\t\tmethod: \"POST\",\n"));
		assert!(source.contains("\t\tpattern: \"/users\",\n"));
		assert!(source.contains("\t\t__i: null as unknown as UserInput,\n"));
		assert!(source.contains("\t\t__o: null as unknown as User,\n"));
		assert!(source.contains(&format!("const {PRIVATE_VIEW_CONTRACTS_IDENTIFIER} = [")));
		assert!(source.contains("\t\tparams: [\"id\"],\n"));
		assert!(source.contains("\t\tpattern: \"/users/:id\",\n"));
		assert!(source.contains("\t\t__i: null as unknown as undefined,\n"));
		assert!(source.contains("\t\t__o: null as unknown as User,\n"));
		assert!(source.contains("export type User = {\n\t\"full-name\": string;\n};"));
		assert!(!source.contains("declare const "));
		assert!(!source.contains("readonly "));
		assert!(!source.contains("input_schema"));
		assert!(!source.contains("search_schema"));
		assert!(!source.contains("export interface"));
		assert!(!source.contains(VIEW_CONTRACTS_TYPE_NAME));
		assert!(!source.contains(RESOURCE_CONTRACTS_TYPE_NAME));
	}

	#[test]
	fn generated_contracts_render_empty_public_url_key_type_and_null_output() {
		let mut declarations = FrameworkDeclarations::default();
		declarations.add_resource(ResourceDeclaration::new(
			Method::GET,
			"/ping",
			None,
			None,
			RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
			handler_id("ping"),
		));
		let graph = FrameworkGraph::compile(declarations).unwrap();
		let bundle = ProjectionBundle::compile(&graph);
		let public_filemap = BTreeMap::new();

		let generated = render_typescript_contracts(&bundle, &public_filemap).unwrap();

		assert!(
			generated
				.source()
				.contains("type VormaPublicUrlKey = never;")
		);
		assert!(generated.source().contains("__o: null as unknown as null,"));
		assert!(!generated.source().contains("input_schema"));
	}

	#[test]
	fn generated_contracts_render_form_data_resource_inputs() {
		let mut declarations = FrameworkDeclarations::default();
		declarations.add_resource(ResourceDeclaration::new(
			Method::POST,
			"/upload",
			None,
			None,
			RouteTypeContract::new(TypeRefContract::FormData, TypeRefContract::Unknown),
			handler_id("upload"),
		));
		let graph = FrameworkGraph::compile(declarations).unwrap();
		let bundle = ProjectionBundle::compile(&graph);
		let public_filemap = BTreeMap::new();

		let generated = render_typescript_contracts(&bundle, &public_filemap).unwrap();

		assert!(
			generated
				.source()
				.contains("__i: null as unknown as FormData,")
		);
	}

	#[test]
	fn generated_contracts_render_blob_resource_outputs() {
		let mut declarations = FrameworkDeclarations::default();
		declarations.add_resource(ResourceDeclaration::new(
			Method::GET,
			"/download",
			None,
			None,
			RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Blob),
			handler_id("download"),
		));
		let graph = FrameworkGraph::compile(declarations).unwrap();
		let bundle = ProjectionBundle::compile(&graph);
		let public_filemap = BTreeMap::new();

		let generated = render_typescript_contracts(&bundle, &public_filemap).unwrap();

		assert!(generated.source().contains("__o: null as unknown as Blob,"));
	}

	#[test]
	fn generated_contracts_reject_invalid_type_names() {
		let mut source = String::new();

		let error = render_type_def(
			&TypeDef::Alias {
				key: "bad".to_owned(),
				name: "bad name".to_owned(),
				target: TypeRefContract::String,
			},
			&mut source,
		)
		.unwrap_err();

		assert!(matches!(
			error,
			TypeScriptContractError::InvalidTypeName { .. }
		));
	}

	#[test]
	fn generated_contracts_reject_invalid_named_type_references() {
		let mut source = String::new();

		let error = render_type_def(
			&TypeDef::Alias {
				key: "Alias".to_owned(),
				name: "Alias".to_owned(),
				target: TypeRefContract::Named {
					key: "bad".to_owned(),
					name: "bad name".to_owned(),
				},
			},
			&mut source,
		)
		.unwrap_err();

		assert!(matches!(
			error,
			TypeScriptContractError::InvalidTypeReferenceName { .. }
		));
	}

	#[test]
	fn graph_rejects_invalid_type_names_before_generation() {
		let mut declarations = FrameworkDeclarations::default();
		declarations.add_type_def(TypeDef::Alias {
			key: "bad".to_owned(),
			name: "bad name".to_owned(),
			target: TypeRefContract::String,
		});

		let error = FrameworkGraph::compile(declarations).unwrap_err();

		assert!(matches!(error, GraphError::InvalidTypeDef { .. }));
	}

	fn record_def(name: &str) -> TypeDef {
		TypeDef::Record {
			key: name.to_owned(),
			name: name.to_owned(),
			fields: vec![FieldDef::new("value", TypeRefContract::String, false)],
		}
	}

	#[test]
	fn generated_contracts_sort_type_defs_by_name_regardless_of_registration_order() {
		let mut declarations = FrameworkDeclarations::default();
		declarations.add_type_def(record_def("Zebra"));
		declarations.add_type_def(record_def("Alpha"));
		declarations.add_type_def(record_def("Middle"));
		declarations.add_view(ViewDeclaration::new(
			"/",
			"root.tsx",
			serde_json::json!({}),
			RouteTypeContract::new(TypeRefContract::Unit, named_type("Zebra", "Zebra")),
			handler_id("view"),
		));
		declarations.add_resource(ResourceDeclaration::new(
			Method::POST,
			"/things",
			None,
			None,
			RouteTypeContract::new(named_type("Alpha", "Alpha"), named_type("Middle", "Middle")),
			handler_id("resource"),
		));
		let bundle = ProjectionBundle::compile(&FrameworkGraph::compile(declarations).unwrap());

		let generated = render_typescript_contracts(&bundle, &BTreeMap::new()).unwrap();
		let source = generated.source();

		let alpha = source.find("export type Alpha = {").unwrap();
		let middle = source.find("export type Middle = {").unwrap();
		let zebra = source.find("export type Zebra = {").unwrap();
		assert!(alpha < middle, "{source}");
		assert!(middle < zebra, "{source}");
	}

	#[test]
	fn generated_contracts_are_byte_deterministic_across_renders() {
		let first =
			render_typescript_contracts(&ProjectionBundle::compile(&graph()), &public_filemap())
				.unwrap();
		let second =
			render_typescript_contracts(&ProjectionBundle::compile(&graph()), &public_filemap())
				.unwrap();

		assert_eq!(first.source(), second.source());
	}

	#[test]
	fn generated_contracts_hold_formatting_invariants_for_all_input_combinations() {
		// Names register intentionally out of alphabetical order so the
		// sorted-output invariant is exercised, not satisfied by accident.
		let def_levels: Vec<(&str, Vec<TypeDef>)> = vec![
			("no defs", Vec::new()),
			("one record", vec![record_def("ZzRecord")]),
			(
				"record + alias + enum",
				vec![
					record_def("ZzRecord"),
					TypeDef::Alias {
						key: "MmAlias".to_owned(),
						name: "MmAlias".to_owned(),
						target: TypeRefContract::String,
					},
					TypeDef::StringEnum {
						key: "AaEnum".to_owned(),
						name: "AaEnum".to_owned(),
						variants: vec!["asc".to_owned(), "desc".to_owned()],
					},
				],
			),
			(
				"record + alias + enum + raw",
				vec![
					record_def("ZzRecord"),
					TypeDef::Alias {
						key: "MmAlias".to_owned(),
						name: "MmAlias".to_owned(),
						target: TypeRefContract::String,
					},
					TypeDef::StringEnum {
						key: "AaEnum".to_owned(),
						name: "AaEnum".to_owned(),
						variants: vec!["asc".to_owned(), "desc".to_owned()],
					},
					TypeDef::Raw {
						key: "RrRaw".to_owned(),
						name: "RrRaw".to_owned(),
						body: vec![RawTsPart::Text("string | number".to_owned())],
					},
				],
			),
		];
		let view_levels: Vec<(&str, Vec<ViewDeclaration>)> = vec![
			("no views", Vec::new()),
			(
				"one view",
				vec![ViewDeclaration::new(
					"/",
					"root.tsx",
					serde_json::json!({}),
					RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
					handler_id("root"),
				)],
			),
			(
				"params + splat views",
				vec![
					ViewDeclaration::new(
						"/",
						"root.tsx",
						serde_json::json!({}),
						RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
						handler_id("root"),
					),
					ViewDeclaration::new(
						"/users/:id",
						"user.tsx",
						serde_json::json!({"q": "string"}),
						RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
						handler_id("user"),
					),
					ViewDeclaration::new(
						"/files/*",
						"files.tsx",
						serde_json::json!({}),
						RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
						handler_id("files"),
					),
				],
			),
		];
		let resource_levels: Vec<(&str, Vec<ResourceDeclaration>)> = vec![
			("no resources", Vec::new()),
			(
				"one query resource",
				vec![ResourceDeclaration::new(
					Method::GET,
					"/ping",
					None,
					None,
					RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
					handler_id("ping"),
				)],
			),
			(
				"query + mutation resources",
				vec![
					ResourceDeclaration::new(
						Method::GET,
						"/ping",
						None,
						None,
						RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
						handler_id("ping"),
					),
					ResourceDeclaration::new(
						Method::POST,
						"/things",
						None,
						None,
						RouteTypeContract::new(TypeRefContract::Unit, TypeRefContract::Null),
						handler_id("things"),
					),
				],
			),
			(
				"form-data resource",
				vec![ResourceDeclaration::new(
					Method::POST,
					"/upload",
					None,
					None,
					RouteTypeContract::new(TypeRefContract::FormData, TypeRefContract::Null),
					handler_id("upload"),
				)],
			),
		];
		let filemap_levels: Vec<(&str, BTreeMap<String, String>)> = vec![
			("no assets", BTreeMap::new()),
			(
				"one asset",
				BTreeMap::from([("app.css".to_owned(), "/static/app.h.css".to_owned())]),
			),
			(
				"three assets",
				BTreeMap::from([
					("app.css".to_owned(), "/static/app.h.css".to_owned()),
					("logo.svg".to_owned(), "/static/logo.h.svg".to_owned()),
					("font.woff2".to_owned(), "/static/font.h.woff2".to_owned()),
				]),
			),
		];
		let extra_levels: Vec<(&str, Option<&str>)> = vec![
			("no extra source", None),
			(
				"extra source with newline",
				Some("export const extra = 1;\n"),
			),
			(
				"extra source without newline",
				Some("export const extra = 1;"),
			),
		];

		let mut combinations = 0;
		for (def_label, defs) in &def_levels {
			for (view_label, views) in &view_levels {
				for (resource_label, resources) in &resource_levels {
					for (filemap_label, filemap) in &filemap_levels {
						for (extra_label, extra) in &extra_levels {
							combinations += 1;
							let label = format!(
								"{def_label} / {view_label} / {resource_label} / {filemap_label} / {extra_label}"
							);
							let build = || {
								let mut declarations = match extra {
									Some(extra) => FrameworkDeclarations::new(
										FrameworkConfig::new("/static/").with_build_inputs(
											BuildInputConfig::new(
												ServerBuildTarget::new("pkg", "bin"),
												"/tmp/app",
												"dist",
												FrontendBuildInputs::new(
													"react",
													"pnpm",
													".",
													"vite.config.ts",
													"src/entry.tsx",
													"public",
													"src/critical.css",
												),
												"src/vorma.gen.ts",
												DevWatchConfig::default(),
											)
											.with_generated_typescript_extra_source(*extra),
										),
									),
									None => FrameworkDeclarations::default(),
								};
								for def in defs {
									declarations.add_type_def(def.clone());
								}
								for view in views {
									declarations.add_view(view.clone());
								}
								for resource in resources {
									declarations.add_resource(resource.clone());
								}
								let graph = FrameworkGraph::compile(declarations)
									.unwrap_or_else(|error| panic!("{label}: {error:?}"));
								render_typescript_contracts(
									&ProjectionBundle::compile(&graph),
									filemap,
								)
								.unwrap_or_else(|error| panic!("{label}: {error}"))
							};

							let first = build();
							let second = build();
							assert_eq!(
								first.source(),
								second.source(),
								"{label}: nondeterministic output"
							);

							let source = first.source();
							assert!(
								source.starts_with(GENERATED_HEADER),
								"{label}: missing header"
							);
							assert!(
								!source.contains("\n\n\n"),
								"{label}: double blank line\n{source}"
							);
							assert!(source.ends_with('\n'), "{label}: missing trailing newline");
							assert!(
								!source.ends_with("\n\n"),
								"{label}: trailing blank line\n{source}"
							);
							assert!(
								!source.contains(" \n") && !source.contains("\t\n"),
								"{label}: trailing whitespace\n{source}"
							);

							let mut def_positions = Vec::new();
							for def in sorted_type_defs(defs) {
								let needle = format!("export type {} = ", def.name());
								let position = source.find(&needle).unwrap_or_else(|| {
									panic!("{label}: missing def {}\n{source}", def.name())
								});
								def_positions.push(position);
							}
							assert!(
								def_positions.is_sorted(),
								"{label}: type defs out of order\n{source}"
							);
						}
					}
				}
			}
		}
		assert_eq!(combinations, 432);
	}
}
