//! Vite plugin contract generation for the TypeScript package.
//!
//! The TypeScript Vite plugin consumes a fixed contract from the build-entry
//! RPC server: transport constants (env keys, token header, paths) plus the
//! config response and RPC request shapes. Instead of hand-mirroring those in
//! TypeScript, this module renders them from the Rust definitions into
//! `packages/vorma/vite/plugin_contract.gen.ts`, and a golden test pins the
//! committed file to the rendered output.

use vorma::tsgen::{TsExtraType, TypePhase};

use crate::typescript_contracts::{
	TypeScriptContractError, normalize_trailing_newlines, render_type_def, sorted_type_defs,
};
use crate::vite_plugin_contract::{
	VITE_PLUGIN_ASSETS_CHANGED_PATH, VITE_PLUGIN_BASE_PATH, VITE_PLUGIN_CONFIG_CHANGED_PATH,
	VITE_PLUGIN_LOOPBACK_HOST, VITE_PLUGIN_PUBLIC_URL_PREFIX, VITE_PLUGIN_RPC_PATH,
	VITE_PLUGIN_SERVER_PORT_ENV_KEY, VITE_PLUGIN_SERVER_TOKEN_ENV_KEY, VITE_PLUGIN_TOKEN_HEADER,
	VitePluginConfig, VitePluginRpcRequest,
};

const GENERATED_HEADER: &str = "\
// Code generated by Vorma. DO NOT EDIT.
//
// Vite plugin contract constants and types, rendered from the Rust
// definitions in crates/vorma-build/src/vite_plugin_contract.rs (see
// crates/vorma-build/src/vite_plugin_ts_contracts.rs). Regenerate with:
//
//   VORMA_UPDATE_WIRE_CONTRACTS=1 cargo test -p vorma-build vite_plugin_ts_contracts

";

/// TypeScript constant names paired with the Rust constants they project.
const PLUGIN_CONSTANTS: &[(&str, &str)] = &[
	("env_key", VITE_PLUGIN_SERVER_PORT_ENV_KEY),
	("token_env_key", VITE_PLUGIN_SERVER_TOKEN_ENV_KEY),
	("token_header", VITE_PLUGIN_TOKEN_HEADER),
	("loopback_host", VITE_PLUGIN_LOOPBACK_HOST),
	("plugin_base_path", VITE_PLUGIN_BASE_PATH),
	("rpc_path", VITE_PLUGIN_RPC_PATH),
	("cfg_changed_path", VITE_PLUGIN_CONFIG_CHANGED_PATH),
	("assets_changed_path", VITE_PLUGIN_ASSETS_CHANGED_PATH),
	("public_url_prefix", VITE_PLUGIN_PUBLIC_URL_PREFIX),
];

/*
Adding a request variant breaks this match until a sample is added below, so
the rendered union can never silently miss one.
*/
fn assert_rpc_request_samples_cover_every_variant(sample: &VitePluginRpcRequest) {
	match sample {
		VitePluginRpcRequest::Cfg => {}
		VitePluginRpcRequest::Hash { .. } => {}
		VitePluginRpcRequest::SetPort { .. } => {}
	}
}

fn rpc_request_samples() -> Vec<VitePluginRpcRequest> {
	let samples = vec![
		VitePluginRpcRequest::Cfg,
		VitePluginRpcRequest::Hash {
			src_path: "sample".to_owned(),
		},
		VitePluginRpcRequest::SetPort { port: 1 },
	];
	for sample in &samples {
		assert_rpc_request_samples_cover_every_variant(sample);
	}
	samples
}

/// Render the Vite plugin contract TypeScript module.
pub(crate) fn render_vite_plugin_ts_contracts() -> Result<String, VitePluginTsContractError> {
	let mut source = String::from(GENERATED_HEADER);
	for (ts_name, value) in PLUGIN_CONSTANTS {
		let value =
			serde_json::to_string(value).map_err(|error| VitePluginTsContractError::Render {
				message: error.to_string(),
			})?;
		source.push_str(&format!("export const {ts_name} = {value};\n"));
	}
	source.push('\n');
	let config =
		TsExtraType::of_for::<VitePluginConfig>(TypePhase::Serialize).map_err(|error| {
			VitePluginTsContractError::Render {
				message: error.to_string(),
			}
		})?;
	for type_def in sorted_type_defs(config.__type_defs()) {
		render_type_def(type_def, &mut source)
			.map_err(|source| VitePluginTsContractError::TypeScript { source })?;
	}
	source.push('\n');
	render_rpc_request_union(&mut source)?;
	normalize_trailing_newlines(&mut source);
	Ok(source)
}

/// Render the RPC request union from real serde serialization of every
/// variant, so tag and field names cannot drift from the Rust enum.
fn render_rpc_request_union(source: &mut String) -> Result<(), VitePluginTsContractError> {
	source.push_str("export type RpcRequest =");
	for sample in rpc_request_samples() {
		let serialized =
			serde_json::to_value(&sample).map_err(|error| VitePluginTsContractError::Render {
				message: error.to_string(),
			})?;
		let serde_json::Value::Object(fields) = serialized else {
			return Err(VitePluginTsContractError::Render {
				message: "RPC request sample did not serialize to an object".to_owned(),
			});
		};
		let serde_json::Value::String(method) = &fields["method"] else {
			return Err(VitePluginTsContractError::Render {
				message: "RPC request sample is missing its method tag".to_owned(),
			});
		};
		source.push_str(&format!("\n\t| {{ method: \"{method}\""));
		let mut field_names = fields.keys().cloned().collect::<Vec<_>>();
		field_names.sort();
		for field_name in field_names {
			if field_name == "method" {
				continue;
			}
			let ts_type = match &fields[&field_name] {
				serde_json::Value::String(_) => "string",
				serde_json::Value::Number(_) => "number",
				serde_json::Value::Bool(_) => "boolean",
				other => {
					return Err(VitePluginTsContractError::Render {
						message: format!(
							"RPC request field {field_name} has unsupported sample shape \
							{other}; extend render_rpc_request_union"
						),
					});
				}
			};
			source.push_str(&format!("; {field_name}: {ts_type}"));
		}
		source.push_str(" }");
	}
	source.push_str(";\n");
	Ok(())
}

/// Vite plugin contract rendering error.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum VitePluginTsContractError {
	/// Type resolution or constant serialization failed.
	Render {
		/// Failure message.
		message: String,
	},
	/// TypeScript type-definition rendering failed.
	TypeScript {
		/// Source contract rendering error.
		source: TypeScriptContractError,
	},
}

impl std::fmt::Display for VitePluginTsContractError {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			Self::Render { message } => write!(f, "render Vite plugin TS contracts: {message}"),
			Self::TypeScript { source } => {
				write!(f, "render Vite plugin TS contract types: {source:?}")
			}
		}
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	const GENERATED_FILE_PATH: &str = concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/../../packages/vorma/vite/plugin_contract.gen.ts"
	);
	const UPDATE_ENV_KEY: &str = "VORMA_UPDATE_WIRE_CONTRACTS";

	#[test]
	fn generated_vite_plugin_ts_contracts_match_committed_file() {
		let rendered = render_vite_plugin_ts_contracts().unwrap();
		if std::env::var(UPDATE_ENV_KEY).is_ok() {
			std::fs::write(GENERATED_FILE_PATH, &rendered)
				.expect("write generated Vite plugin TS file");
			return;
		}
		let committed = std::fs::read_to_string(GENERATED_FILE_PATH).unwrap_or_else(|error| {
			panic!(
				"missing generated Vite plugin TS contracts at {GENERATED_FILE_PATH} ({error}); \
				run {UPDATE_ENV_KEY}=1 cargo test -p vorma-build vite_plugin_ts_contracts"
			)
		});
		assert_eq!(
			committed, rendered,
			"generated Vite plugin TS contracts drifted from the Rust definitions; regenerate \
			with {UPDATE_ENV_KEY}=1 cargo test -p vorma-build vite_plugin_ts_contracts"
		);
	}

	#[test]
	fn rendered_plugin_contracts_declare_config_and_rpc_union() {
		let rendered = render_vite_plugin_ts_contracts().unwrap();
		assert!(rendered.contains("export const token_header = \"x-vorma-vite-plugin-token\";"));
		assert!(rendered.contains("export const public_url_prefix = \"@public/\";"));
		assert!(rendered.contains("export type VitePluginConfig = {"));
		assert!(rendered.contains("\tpublic_static_base_path: string;"));
		assert!(rendered.contains("\tdedupe_list: Array<string>;"));
		assert!(rendered.contains("| { method: \"cfg\" }"));
		assert!(rendered.contains("| { method: \"hash\"; src_path: string }"));
		assert!(rendered.contains("| { method: \"set_port\"; port: number }"));
	}
}
