//! Framework-level wire contract generation for the TypeScript package.
//!
//! The browser runtime consumes a fixed wire contract from the server: the
//! view payload envelope, prepared head elements, and protocol header/query
//! constants. Instead of hand-mirroring those in TypeScript, this module
//! renders them from the Rust definitions in `vorma` into
//! `packages/vorma/core/wire_contracts.gen.ts`, and a golden test pins the
//! committed file to the rendered output.

use vorma::tsgen::{TsExtraType, TypePhase};
use vorma_contract::constants::VORMA_DATA_JSON_SCRIPT_EL_ID;
use vorma_contract::wire::{
	BUILD_SKEW_HEADER, CLIENT_ACCEPTS_REDIRECT_HEADER, CLIENT_BUILD_ID_HEADER,
	CLIENT_REDIRECT_HEADER, RESOURCE_BODY_HEADER, SsrPayload, VORMA_JSON_QUERY_KEY, ViewPayload,
};

use crate::typescript_contracts::{
	TypeScriptContractError, normalize_trailing_newlines, render_type_def, sorted_type_defs,
};

const GENERATED_HEADER: &str = "\
// Code generated by Vorma. DO NOT EDIT.
//
// Framework wire-contract types and constants, rendered from the Rust
// definitions in crates/vorma (see crates/vorma-build/src/wire_ts_contracts.rs).
// Regenerate with:
//
//   VORMA_UPDATE_WIRE_CONTRACTS=1 cargo test -p vorma-build wire_ts_contracts

";

/// TypeScript constant names paired with the Rust constants they project.
const WIRE_CONSTANTS: &[(&str, &str)] = &[
	("VORMA_JSON_KEY", VORMA_JSON_QUERY_KEY),
	("DATA_SCRIPT_ID", VORMA_DATA_JSON_SCRIPT_EL_ID),
	("BUILD_ID_HEADER", CLIENT_BUILD_ID_HEADER),
	("X_VORMA_BUILD_SKEW", BUILD_SKEW_HEADER),
	("X_CLIENT_REDIRECT", CLIENT_REDIRECT_HEADER),
	("X_VORMA_RESOURCE_BODY", RESOURCE_BODY_HEADER),
	("X_ACCEPTS_CLIENT_REDIRECT", CLIENT_ACCEPTS_REDIRECT_HEADER),
];

/// Render the framework wire-contract TypeScript module.
pub(crate) fn render_wire_ts_contracts() -> Result<String, WireTsContractError> {
	let mut source = String::from(GENERATED_HEADER);
	for (ts_name, value) in WIRE_CONSTANTS {
		let value = serde_json::to_string(value).map_err(|error| WireTsContractError::Render {
			message: error.to_string(),
		})?;
		source.push_str(&format!("export const {ts_name} = {value};\n"));
	}
	source.push('\n');
	let payload = TsExtraType::of_for::<ViewPayload>(TypePhase::Serialize).map_err(|error| {
		WireTsContractError::Render {
			message: error.to_string(),
		}
	})?;
	for (index, type_def) in sorted_type_defs(payload.__type_defs()).iter().enumerate() {
		if index > 0 {
			source.push('\n');
		}
		render_type_def(type_def, &mut source)
			.map_err(|source| WireTsContractError::TypeScript { source })?;
	}
	source.push('\n');
	render_ssr_payload_type(&mut source)?;
	normalize_trailing_newlines(&mut source);
	Ok(source)
}

/// Render the SSR data-script payload type.
///
/// `SsrPayload` flattens `ViewPayload` (which the TsGen derive cannot express),
/// so the intersection is rendered here — with the extra fields discovered from
/// real serde serialization rather than hand-listed, so a new field on the Rust
/// struct cannot silently miss the generated type.
fn render_ssr_payload_type(source: &mut String) -> Result<(), WireTsContractError> {
	let sample = SsrPayload {
		client_build_id: "sample".to_owned(),
		is_dev: true,
		deployment_id: "sample".to_owned(),
		view_payload: ViewPayload::default(),
	};
	let serialized =
		serde_json::to_value(&sample).map_err(|error| WireTsContractError::Render {
			message: error.to_string(),
		})?;
	let serde_json::Value::Object(fields) = serialized else {
		return Err(WireTsContractError::Render {
			message: "SsrPayload sample did not serialize to an object".to_owned(),
		});
	};
	// A defaulted ViewPayload flattens to nothing, so the remaining keys are
	// exactly the SsrPayload-only fields. All carry skip_serializing_if, so
	// they are optional on the wire.
	let mut field_names = fields.keys().cloned().collect::<Vec<_>>();
	field_names.sort();
	source.push_str("export type SsrPayload = ViewPayload & {\n");
	for field_name in field_names {
		let ts_type = match &fields[&field_name] {
			serde_json::Value::String(_) => "string",
			serde_json::Value::Bool(_) => "boolean",
			serde_json::Value::Number(_) => "number",
			other => {
				return Err(WireTsContractError::Render {
					message: format!(
						"SsrPayload field {field_name} has unsupported sample shape {other}; \
						extend render_ssr_payload_type"
					),
				});
			}
		};
		source.push_str(&format!("\t{field_name}?: {ts_type};\n"));
	}
	source.push_str("};\n");
	Ok(())
}

/// Wire contract rendering error.
#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum WireTsContractError {
	/// Type resolution or constant serialization failed.
	Render {
		/// Failure message.
		message: String,
	},
	/// TypeScript type-definition rendering failed.
	TypeScript {
		/// Source contract rendering error.
		source: TypeScriptContractError,
	},
}

impl std::fmt::Display for WireTsContractError {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			Self::Render { message } => write!(f, "render wire TS contracts: {message}"),
			Self::TypeScript { source } => {
				write!(f, "render wire TS contract types: {source:?}")
			}
		}
	}
}

#[cfg(test)]
mod tests {
	use super::*;

	const GENERATED_FILE_PATH: &str = concat!(
		env!("CARGO_MANIFEST_DIR"),
		"/../../packages/vorma/core/wire_contracts.gen.ts"
	);
	const UPDATE_ENV_KEY: &str = "VORMA_UPDATE_WIRE_CONTRACTS";

	#[test]
	fn generated_wire_ts_contracts_match_committed_file() {
		let rendered = render_wire_ts_contracts().unwrap();
		if std::env::var(UPDATE_ENV_KEY).is_ok() {
			std::fs::write(GENERATED_FILE_PATH, &rendered).expect("write generated wire TS file");
			return;
		}
		let committed = std::fs::read_to_string(GENERATED_FILE_PATH).unwrap_or_else(|error| {
			panic!(
				"missing generated wire TS contracts at {GENERATED_FILE_PATH} ({error}); \
				run {UPDATE_ENV_KEY}=1 cargo test -p vorma-build wire_ts_contracts"
			)
		});
		assert_eq!(
			committed, rendered,
			"generated wire TS contracts drifted from the Rust definitions; regenerate with \
			{UPDATE_ENV_KEY}=1 cargo test -p vorma-build wire_ts_contracts"
		);
	}

	#[test]
	fn rendered_wire_contracts_declare_payload_and_constants() {
		let rendered = render_wire_ts_contracts().unwrap();
		assert!(rendered.contains("export const VORMA_JSON_KEY = \"vorma-json\";"));
		assert!(rendered.contains("export type ViewPayload = {"));
		assert!(rendered.contains("export type HeadElement = {"));
		assert!(rendered.contains("export type SsrPayload = ViewPayload & {"));
		assert!(rendered.contains("\tclient_build_id?: string;"));
		assert!(rendered.contains("\tis_dev?: boolean;"));
		assert!(rendered.contains("\tdeployment_id?: string;"));
	}
}
