/////////////////////////////////////////////////////////////////////
/////// Generated by tsgen. DO NOT EDIT.
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
/////// Collection:
/////////////////////////////////////////////////////////////////////

const routes = [
	{
		_type: "loader",
		isRootData: true,
		pattern: "/",
		phantomOutputType: null as unknown as RootLoaderOutput,
	},
	{
		_type: "loader",
		params: ["bucket"],
		pattern: "/slow/:bucket",
		phantomOutputType: null as unknown as SlowLoaderOutput,
	},
	{
		_type: "loader",
		params: ["id"],
		pattern: "/users/:id",
		phantomOutputType: null as unknown as UserLoaderOutput,
	},
	{
		_type: "loader",
		pattern: "/_index",
		phantomOutputType: null as unknown as HomeLoaderOutput,
	},
	{
		_type: "loader",
		pattern: "/explode",
	},
	{
		_type: "loader",
		pattern: "/hmr-probe",
	},
	{
		_type: "loader",
		pattern: "/mutation-lab",
	},
	{
		_type: "loader",
		pattern: "/navigation-race",
	},
	{
		_type: "loader",
		pattern: "/odd-shapes",
		phantomOutputType: null as unknown as OddShapesLoaderOutput,
	},
	{
		_type: "loader",
		pattern: "/redirect-chain/end",
		phantomOutputType: null as unknown as RedirectChainEndLoaderOutput,
	},
	{
		_type: "loader",
		pattern: "/redirect-chain/middle",
	},
	{
		_type: "loader",
		pattern: "/redirect-chain/start",
	},
	{
		_type: "mutation",
		pattern: "/always-fail",
	},
	{
		_type: "mutation",
		pattern: "/echo-body",
		phantomInputType: null as unknown as EchoBodyInput,
		phantomOutputType: null as unknown as EchoBodyOutput,
	},
	{
		_type: "mutation",
		pattern: "/echo-complex-body",
		phantomInputType: null as unknown as EchoComplexBodyInput,
		phantomOutputType: null as unknown as EchoComplexBodyOutput,
	},
	{
		_type: "mutation",
		pattern: "/increment-count",
		phantomOutputType: null as unknown as IncrementCountOutput,
	},
	{
		_type: "mutation",
		pattern: "/reset-count",
		phantomOutputType: null as unknown as IncrementCountOutput,
	},
	{
		_type: "mutation",
		pattern: "/slow-increment",
		phantomInputType: null as unknown as SlowIncrementInput,
		phantomOutputType: null as unknown as SlowIncrementOutput,
	},
	{
		_type: "mutation",
		pattern: "/submit-and-redirect",
		phantomInputType: null as unknown as FormData,
	},
] as const;

/////////////////////////////////////////////////////////////////////
/////// Ad Hoc Types:
/////////////////////////////////////////////////////////////////////

export type EchoBodyInput = {
	value: string;
	amount: number;
};

export type EchoBodyOutput = {
	value: string;
	amount: number;
};

export type EchoComplexBodyInput = {
	title: string;
	flags: Array<boolean>;
	scores: Array<number>;
	metadata: Record<string, string>;
};

export type EchoComplexBodyOutput = {
	title: string;
	flags: Array<boolean>;
	scores: Array<number>;
	metadata: Record<string, string>;
	scoreTotal: number;
};

export type HomeLoaderOutput = {
	message: string;
	count: number;
};

export type IncrementCountOutput = {
	count: number;
};

export type OddShapeTimelineRow = {
	label: string;
	step: number;
};

export type OddShapesLoaderOutput = {
	emptyWords: Array<string>;
	numberMatrix: Array<Array<number>>;
	optionalNote?: string;
	nestedFlags: Record<string, Array<boolean>>;
	metadata: Record<string, string>;
	mixedNumbers: Record<string, number>;
	timeline: Array<OddShapeTimelineRow>;
};

export type RedirectChainEndLoaderOutput = {
	hop: string;
	terminal: string;
};

export type RootLoaderOutput = {
	mode: string;
};

export type SlowIncrementInput = {
	delayMs: number;
	tag: string;
};

export type SlowIncrementOutput = {
	count: number;
	delayMs: number;
	tag: string;
};

export type SlowLoaderOutput = {
	bucket: string;
	token: string;
	delayMs: number;
	sequence: number;
};

export type UserLoaderOutput = {
	id: string;
	query: string;
	isDev: boolean;
	buildTag: string;
};

/////////////////////////////////////////////////////////////////////
/////// Extra TS Code:
/////////////////////////////////////////////////////////////////////

type VormaRootData = Extract<
	(typeof routes)[number],
	{ isRootData: true }
>["phantomOutputType"];

export type VormaApp = {
	routes: typeof routes;
	appConfig: typeof vormaAppConfig;
	rootData: VormaRootData;
};

export const vormaAppConfig = {
	actionsRouterMountRoot: "/api/",
	actionsDynamicRune: ":",
	actionsSplatRune: "*",
	loadersDynamicRune: ":",
	loadersSplatRune: "*",
	loadersExplicitIndexSegmentIdentifier: "_index",
	__phantom: null as unknown as VormaApp,
} as const;

import type {
	VormaLoaderPattern,
	VormaMutationInput,
	VormaMutationOutput,
	VormaMutationPattern,
	VormaMutationProps,
	VormaQueryInput,
	VormaQueryOutput,
	VormaQueryPattern,
	VormaQueryProps,
} from "vorma/client";
import type { VormaRouteProps } from "vorma/react";

export type QueryPattern = VormaQueryPattern<VormaApp>;
export type QueryProps<P extends QueryPattern> = VormaQueryProps<VormaApp, P>;
export type QueryInput<P extends QueryPattern> = VormaQueryInput<VormaApp, P>;
export type QueryOutput<P extends QueryPattern> = VormaQueryOutput<VormaApp, P>;

export type MutationPattern = VormaMutationPattern<VormaApp>;
export type MutationProps<P extends MutationPattern> = VormaMutationProps<VormaApp, P>;
export type MutationInput<P extends MutationPattern> = VormaMutationInput<VormaApp, P>;
export type MutationOutput<P extends MutationPattern> = VormaMutationOutput<VormaApp, P>;

export type RouteProps<P extends VormaLoaderPattern<VormaApp>> = VormaRouteProps<VormaApp, P>;

/////////////////////////////////////////////////////////////////////
/////// Vorma Vite Config:
/////////////////////////////////////////////////////////////////////

import { staticPublicAssetMap } from "./filemap";
export { staticPublicAssetMap };
export type StaticPublicAsset = keyof typeof staticPublicAssetMap;

declare global {
	function waveBuildtimeURL(staticPublicAsset: StaticPublicAsset): string;
}

export const publicPathPrefix = "/";

export function waveRuntimeURL(originalPublicURL: StaticPublicAsset) {
	const hashedPublicURL = staticPublicAssetMap[originalPublicURL];
	if (!hashedPublicURL) {
		throw new Error("Wave public URL lookup miss: " + originalPublicURL);
	}
	return publicPathPrefix + hashedPublicURL;
}

export const vormaViteConfig = {
	rollupInput: [
		"frontend/src_react/components/error_boundary.tsx",
		"frontend/src_react/components/hmr_probe.tsx",
		"frontend/src_react/components/home.tsx",
		"frontend/src_react/components/mutation_lab.tsx",
		"frontend/src_react/components/navigation_race.tsx",
		"frontend/src_react/components/root.tsx",
		"frontend/src_react/components/slow.tsx",
		"frontend/src_react/components/user.tsx",
		"frontend/src_react/vorma.entry.tsx"
	],
	publicPathPrefix,
	staticPublicAssetMap,
	buildtimePublicURLFuncName: "waveBuildtimeURL",
	filemapJSONPath: "frontend/src_react/vorma.gen/filemap.json",
	ignoredPatterns: [
		"**/*.go",
		"**/backend/dist/**/*",
		"**/backend/assets/**/*",
		"**/frontend/src_react/vorma.gen/**/*",
		"**/backend/wave.config.json",
		"**/frontend/src_react/**/*vorma.routes.ts"
	],
	dedupeList: [
		"react",
		"react-dom"
	],
} as const;
