// Code generated by vorma2. DO NOT EDIT.

export const staticPublicAssetMap = {
	"bob.txt": "wave_out_bob_pu4lyj34jf2d.txt",
	"desktop.svg": "wave_out_desktop_z542yudaunts.svg",
	"favicon.svg": "wave_out_favicon_3qoyab3ohlbk.svg",
	"fonts/jetbrains_mono.woff2": "wave_out_fonts_jetbrains_mono_ocupwbzyuo4e.woff2",
	"fonts/jetbrains_mono_ext.woff2": "wave_out_fonts_jetbrains_mono_ext_o7uqyzdwrkdz.woff2",
	"fonts/jetbrains_mono_italic.woff2": "wave_out_fonts_jetbrains_mono_italic_mzgy4nlc67of.woff2",
	"fonts/jetbrains_mono_italic_ext.woff2": "wave_out_fonts_jetbrains_mono_italic_ext_lcjle7tyuc6h.woff2",
	"moon.svg": "wave_out_moon_ewhgithiyjiq.svg",
	"sun.svg": "wave_out_sun_zm5pxgp6eeix.svg",
	"vorma-banner.webp": "wave_out_vorma-banner_kskpp65h3ya2.webp",
	"vorma_internal_route_manifest.json": "wave_out_vorma_internal_route_manifest_xz4zt47sxzbf.json",
	"wave_internal_non_critical_css.css": "wave_out_wave_internal_non_critical_css_2gagxv5tqlsb.css",
	"wave_internal_public_filemap.json": "wave_out_wave_internal_public_filemap_bsalieqqczuk.json",
} as const;

export type StaticPublicAsset = keyof typeof staticPublicAssetMap;
