// Code generated by Vorma. DO NOT EDIT.

import type { VormaClientSeed } from "vorma/react";

export const vormaClientSeed = {
	__vorma_views: null as unknown as typeof __vorma_views,
	__vorma_resources: null as unknown as typeof __vorma_resources,
} as const satisfies VormaClientSeed;

declare global {
	/** Argument must be a static string literal. */
	function vormaPublicUrl(k: VormaPublicUrlKey): string;
}

const vormaPublicUrlKeys = ["mark.svg"] as const;

type VormaPublicUrlKey = `${"" | "/"}${(typeof vormaPublicUrlKeys)[number]}`;

const __vorma_resources = [
	{
		method: "POST",
		pattern: "/api/session",
		__i: null as unknown as LoginInput,
		__o: null as unknown as LoginOutput,
	},
	{
		method: "DELETE",
		pattern: "/api/session",
		__i: null as unknown as undefined,
		__o: null as unknown as undefined,
	},
	{
		method: "POST",
		pattern: "/api/stories",
		__i: null as unknown as FormData,
		__o: null as unknown as undefined,
	},
	{
		method: "POST",
		params: ["story_id"],
		pattern: "/api/stories/:story_id/vote",
		__i: null as unknown as undefined,
		__o: null as unknown as VoteOutput,
	},
	{
		method: "POST",
		params: ["story_id"],
		pattern: "/api/stories/:story_id/comments",
		__i: null as unknown as CreateCommentInput,
		__o: null as unknown as CreateCommentOutput,
	},
	{
		method: "GET",
		pattern: "/api/search",
		__i: null as unknown as SearchInput,
		__o: null as unknown as SearchOutput,
	},
	{
		method: "POST",
		params: ["story_id"],
		pattern: "/api/mod/stories/:story_id/kill",
		__i: null as unknown as undefined,
		__o: null as unknown as undefined,
	},
	{
		method: "POST",
		params: ["story_id"],
		pattern: "/api/mod/stories/:story_id/restore",
		__i: null as unknown as undefined,
		__o: null as unknown as undefined,
	},
	{
		method: "GET",
		params: ["story_id"],
		pattern: "/api/stories/:story_id/attachment",
		__i: null as unknown as undefined,
		__o: null as unknown as Blob,
	},
] as const;

const __vorma_views = [
	{
		pattern: "/",
		__i: null as unknown as undefined,
		__o: null as unknown as LayoutData,
	},
	{
		parents: ["/"],
		pattern: "/_index",
		__i: null as unknown as FrontInput,
		__o: null as unknown as FrontPage,
	},
	{
		params: ["story_id"],
		parents: ["/"],
		pattern: "/s/:story_id",
		__i: null as unknown as undefined,
		__o: null as unknown as StoryPage,
	},
	{
		parents: ["/"],
		pattern: "/submit",
		__i: null as unknown as undefined,
		__o: null as unknown as SubmitPage,
	},
	{
		params: ["username"],
		parents: ["/"],
		pattern: "/u/:username",
		__i: null as unknown as undefined,
		__o: null as unknown as UserPage,
	},
	{
		params: ["username"],
		parents: ["/", "/u/:username"],
		pattern: "/u/:username/comments",
		__i: null as unknown as undefined,
		__o: null as unknown as UserCommentsPage,
	},
	{
		parents: ["/"],
		pattern: "/docs",
		__i: null as unknown as undefined,
		__o: null as unknown as DocsIndexPage,
	},
	{
		parents: ["/", "/docs"],
		pattern: "/docs/*",
		__i: null as unknown as undefined,
		__o: null as unknown as DocsPageView,
	},
	{
		parents: ["/"],
		pattern: "/search",
		__i: null as unknown as SearchPageInput,
		__o: null as unknown as SearchPage,
	},
	{
		parents: ["/"],
		pattern: "/mod",
		__i: null as unknown as undefined,
		__o: null as unknown as ModPage,
	},
	{
		parents: ["/", "/mod"],
		pattern: "/mod/diagnostics",
		__i: null as unknown as undefined,
		__o: null as unknown as ModDiagnosticsPage,
	},
	{
		parents: ["/"],
		pattern: "/*",
		__i: null as unknown as undefined,
		__o: null as unknown as NotFoundPage,
	},
] as const;

export type Comment = {
	id: number;
	parent_id: number | null;
	author: string;
	body: string;
	created_at: number;
	killed: boolean;
};

export type CreateCommentInput = {
	body: string;
	parent_id?: number | null;
};

export type CreateCommentOutput = {
	comment_id: number;
};

export type DocsIndexPage = {
	index: Array<DocsPage>;
};

export type DocsPage = {
	slug: string;
	title: string;
	body: string;
};

export type DocsPageView = {
	page: DocsPage | null;
};

export type FrontInput = {
	page?: number | null;
};

export type FrontPage = {
	stories: Array<Story>;
	page: number;
	has_more: boolean;
};

export type KeyboardShortcut = {
	keys: string;
	action: string;
};

export type LayoutData = {
	app_name: string;
	mark_url: string;
	current_user: User | null;
};

export type LoginInput = {
	username: string;
};

export type LoginOutput = {
	user: User;
};

export type ModDiagnosticsPage = Record<never, never>;

export type ModLogEntry = {
	id: number;
	moderator: string;
	story_id: number;
	action: string;
	created_at: number;
};

export type ModPage = {
	killed: Array<Story>;
	log: Array<ModLogEntry>;
};

export type NotFoundPage = {
	requested_path: string;
	primary_source: string | null;
	source_tags: Array<string>;
	source_pair_count: number;
};

export type SearchInput = {
	q?: string | null;
	page?: number | null;
};

export type SearchOutput = {
	stories: Array<Story>;
	has_more: boolean;
};

export type SearchPage = {
	q: string;
};

export type SearchPageInput = {
	q?: string | null;
};

export type Story = {
	id: number;
	title: string;
	url: string | null;
	body: string | null;
	author: string;
	points: number;
	comment_count: number;
	created_at: number;
	killed: boolean;
};

export type StoryPage = {
	story: Story | null;
	comments: Array<Comment>;
};

export type SubmitPage = {
	signed_in: boolean;
};

export type User = {
	id: number;
	username: string;
	banned: boolean;
};

export type UserCommentsPage = {
	comments: Array<Comment>;
};

export type UserPage = {
	profile: UserProfile | null;
	stories: Array<Story>;
};

export type UserProfile = {
	username: string;
	karma: number;
	story_count: number;
	comment_count: number;
};

export type VoteOutput = {
	points: number;
};

export const keyboard_shortcuts = [
	{
		action: "focus-search",
		keys: "mod+k",
	},
] as const;

export const front_page_size = 30;

export const csrf_header = "x-board-csrf-token";

export type ModAction = "kill" | "restore";
