[package]
name = "vorma-build"
description = "Vorma build and dev server."
edition.workspace = true
homepage.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true, features = ["ws"] }
blake3.workspace = true
data-encoding.workspace = true
getrandom.workspace = true
globset.workspace = true
http.workspace = true
hyper.workspace = true
hyper-util.workspace = true
lightningcss = { workspace = true, features = ["bundler", "visitor"] }
notify.workspace = true
paranoid = { workspace = true, features = ["local-lock"] }
path-slash.workspace = true
pathdiff.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = [
	"io-util",
	"net",
	"process",
	"rt",
	"signal",
	"sync",
	"time",
] }
url.workspace = true
vorma.workspace = true
vorma-contract.workspace = true
walkdir.workspace = true

[target.'cfg(unix)'.dependencies]
nix.workspace = true

[dev-dependencies]
same-file.workspace = true
tokio = { workspace = true, features = [
	"io-util",
	"macros",
	"net",
	"process",
	"rt",
	"sync",
	"time",
] }
