/////// Generated by Vorma. Do not edit.

/////////////////////////////////////////////////////////////////////
/// Routes:
/////////////////////////////////////////////////////////////////////

const vormaLoaders = [
	{
		pattern: "/",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as RootData,
	},
	{
		parents: ["/"],
		pattern: "/counter",
		__I: null as unknown as CounterInput,
		__O: null as unknown as CounterData,
	},
	{
		parents: ["/"],
		pattern: "/slow",
		__I: null as unknown as SlowInput,
		__O: null as unknown as SlowData,
	},
	{
		parents: ["/"],
		pattern: "/echo",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as EchoData,
	},
	{
		params: ["id"],
		parents: ["/"],
		pattern: "/items/:id",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as ItemData,
	},
	{
		params: ["id"],
		parents: ["/"],
		pattern: "/client/:id",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as ClientData,
	},
	{
		parents: ["/"],
		pattern: "/nested",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as NestedData,
	},
	{
		params: ["id"],
		parents: ["/", "/nested"],
		pattern: "/nested/:id/details",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as NestedDetailData,
	},
	{
		parents: ["/"],
		pattern: "/fail",
		__I: null as unknown as Record<never, never>,
		__O: null as unknown as Record<never, never>,
	},
] as const;

const vormaActions = [
	{
		method: "GET",
		pattern: "/count",
		__I: null as unknown as CountActionInput,
		__O: null as unknown as CountActionData,
	},
	{
		method: "POST",
		pattern: "/echo",
		__I: null as unknown as EchoActionInput,
		__O: null as unknown as EchoActionData,
	},
] as const;

/////////////////////////////////////////////////////////////////////
/// Core Types:
/////////////////////////////////////////////////////////////////////

export type RootData = {
	Name: string;
};

export type CountActionInput = {
	delta: number;
};

export type SlowInput = {
	delay_ms: number;
};

export type CounterInput = {
	n: number;
};

export type EchoActionInput = {
	Message: string;
};

export type ItemData = {
	ID: string;
};

export type SlowData = {
	DelayMS: number;
	Stamp: string;
};

export type EchoData = {
	Message: string;
};

export type CountActionData = {
	Next: number;
};

export type CounterData = {
	Value: number;
};

export type ClientData = {
	ID: string;
	ServerStamp: string;
};

export type NestedData = {
	Section: string;
};

export type NestedDetailData = {
	ID: string;
	Section: string;
};

export type EchoActionData = {
	Message: string;
};

/////////////////////////////////////////////////////////////////////
/// Baked Application Types:
/////////////////////////////////////////////////////////////////////

import type { VormaAppConfig } from "vorma/react";

export const vormaAppConfig = {
	actionsMountRoot: "/api/",
	__phantom_loaders: null as unknown as typeof vormaLoaders,
	__phantom_actions: null as unknown as typeof vormaActions,
} as const satisfies VormaAppConfig;

export type App = typeof vormaAppConfig;

/////////////////////////////////////////////////////////////////////
/// Public URL Setup:
/////////////////////////////////////////////////////////////////////

declare global {
	/** Argument must be a static string literal. */
	function vormaPublicURL(k: VormaPublicURLKey): string;
}

const vormaPublicURLKeys = [".gitkeep"] as const;

type VormaPublicURLKey = `${"" | "/"}${(typeof vormaPublicURLKeys)[number]}`;
