FROM golang:{{.GoVersionForDocker}} AS builder
WORKDIR /app
RUN curl -fsSL https://deb.nodesource.com/setup_{{.NodeMajorVersion}}.x | bash -
RUN apt-get install -y nodejs{{.DockerPackageManagerInstall}}
COPY go.mod go.sum ./
RUN go mod download
COPY . .{{.DockerWorkdirCommand}}
RUN {{.DockerInstallCommand}}
RUN go run ./backend/cmd/build --no-binary
RUN CGO_ENABLED=0 GOOS=linux go build -mod=readonly -o ./backend/.waveout/main ./backend/cmd/serve

FROM alpine
WORKDIR /app
RUN apk --no-cache add ca-certificates
COPY --from=builder {{.DockerBinaryPath}} /
RUN adduser -D serveruser
USER serveruser
ENTRYPOINT ["/main"]
