#!/bin/sh

#####################################################################
#
# You must initialize this pre-commit hook by running the following
# commands:
#
# ```sh
# git config core.hooksPath .hooks
# chmod +x .hooks/pre-commit
# ```
#
# After running the above, this pre-commit hook will run before
# every commit, and if it returns a non-zero exit code, the commit
# will be aborted. You can test the script's behavior by executing
# it directly: `.hooks/pre-commit`.
#
#####################################################################

set -e

run_test() {
  echo "[pre-commit]  INFO   Running cmd '$1'."
  if ! $1; then
    echo "[pre-commit]  ERROR  Cmd '$1' failed. Commit aborted."
    exit 1
  fi
  echo "[pre-commit]  OK     Cmd '$1' passed."
}

run_test "make full-gate"

echo "[pre-commit]  OK     Done."
