/////// Auto-generated by Vorma. Do not edit.

export const staticPublicAssetMap = {
	"desktop.svg": "wave_out_desktop_a070de5fdf91.svg",
	"favicon.svg": "wave_out_favicon_7a601a4cf9c1.svg",
	"fonts/jetbrains_mono.woff2": "wave_out_fonts_jetbrains_mono_f00981b3d5b2.woff2",
	"fonts/jetbrains_mono_ext.woff2": "wave_out_fonts_jetbrains_mono_ext_a900ec3901d5.woff2",
	"fonts/jetbrains_mono_italic.woff2": "wave_out_fonts_jetbrains_mono_italic_fb0fec74e6c1.woff2",
	"fonts/jetbrains_mono_italic_ext.woff2": "wave_out_fonts_jetbrains_mono_italic_ext_eb6da9967829.woff2",
	"moon.svg": "wave_out_moon_2f58ba20833a.svg",
	"sun.svg": "wave_out_sun_55b64396fd71.svg",
	"vorma-banner.webp": "wave_out_vorma-banner_e25e2cbf5da2.webp",
} as const;
