// Code generated by vorma2. DO NOT EDIT.
package autoreg

import (
	_ "site/backend/src/define/action"
	_ "site/backend/src/define/loader"
	_ "site/backend/src/markdown"
	_ "site/backend/src/server"
)
