/////////////////////////////////////////////////////////////////////
/////// Generated by tsgen. DO NOT EDIT.
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
/////// Collection:
/////////////////////////////////////////////////////////////////////

const routes = [
	{
		_type: "loader",
		isRootData: true,
		pattern: "/",
		phantomOutputType: null as unknown as RootData,
	},
	{
		_type: "loader",
		isSplat: true,
		pattern: "/*",
		phantomOutputType: null as unknown as DetailedPage,
	},
	{
		_type: "loader",
		params: ["dyn"],
		pattern: "/__/:dyn",
	},
	{
		_type: "loader",
		pattern: "/_index",
		phantomOutputType: null as unknown as string,
	},
] as const;

/////////////////////////////////////////////////////////////////////
/////// Ad Hoc Types:
/////////////////////////////////////////////////////////////////////

export type DetailedPage = {
	Title?: string;
	Description?: string;
	Date?: string;
	Order?: number;
	Content?: string;
	RawContent?: string;
	URL?: string;
	IsFolder?: boolean;
	Sitemap: Array<SitemapItem>;
	IndexSitemap: Array<SitemapItem>;
	BackItem: string;
};

export type RootData = {
	LatestVersion: string;
};

export type Sitemap = Array<SitemapItem>;

export type SitemapItem = {
	title: string;
	url: string;
	description?: string;
	date?: string;
	isFolder?: boolean;
	isActive?: boolean;
};

/////////////////////////////////////////////////////////////////////
/////// Extra TS Code:
/////////////////////////////////////////////////////////////////////

type VormaRootData = Extract<
	(typeof routes)[number],
	{ isRootData: true }
>["phantomOutputType"];

export type VormaApp = {
	routes: typeof routes;
	appConfig: typeof vormaAppConfig;
	rootData: VormaRootData;
};

export const vormaAppConfig = {
	actionsRouterMountRoot: "/api/",
	actionsDynamicRune: ":",
	actionsSplatRune: "*",
	loadersDynamicRune: ":",
	loadersSplatRune: "*",
	loadersExplicitIndexSegment: "_index",
	__phantom: null as unknown as VormaApp,
} as const;

import type {
	VormaLoaderPattern,
	VormaMutationInput,
	VormaMutationOutput,
	VormaMutationPattern,
	VormaMutationProps,
	VormaQueryInput,
	VormaQueryOutput,
	VormaQueryPattern,
	VormaQueryProps,
} from "vorma/client";
import type { VormaRouteProps } from "vorma/solid";

export type QueryPattern = VormaQueryPattern<VormaApp>;
export type QueryProps<P extends QueryPattern> = VormaQueryProps<VormaApp, P>;
export type QueryInput<P extends QueryPattern> = VormaQueryInput<VormaApp, P>;
export type QueryOutput<P extends QueryPattern> = VormaQueryOutput<VormaApp, P>;

export type MutationPattern = VormaMutationPattern<VormaApp>;
export type MutationProps<P extends MutationPattern> = VormaMutationProps<
	VormaApp,
	P
>;
export type MutationInput<P extends MutationPattern> = VormaMutationInput<
	VormaApp,
	P
>;
export type MutationOutput<P extends MutationPattern> = VormaMutationOutput<
	VormaApp,
	P
>;

export type RouteProps<P extends VormaLoaderPattern<VormaApp>> =
	VormaRouteProps<VormaApp, P>;

/////////////////////////////////////////////////////////////////////
/////// Vorma Vite Config:
/////////////////////////////////////////////////////////////////////

import { staticPublicAssetMap } from "./filemap";
export { staticPublicAssetMap };
export type StaticPublicAsset = keyof typeof staticPublicAssetMap;

declare global {
	function hashedURL(staticPublicAsset: StaticPublicAsset): string;
}

export const publicPathPrefix = "/";

export function waveRuntimeURL(originalPublicURL: StaticPublicAsset) {
	const url = staticPublicAssetMap[originalPublicURL] ?? originalPublicURL;
	return publicPathPrefix + url;
}

export const vormaViteConfig = {
	rollupInput: [
		"frontend/src/components/dyn.tsx",
		"frontend/src/components/home.tsx",
		"frontend/src/components/md.tsx",
		"frontend/src/vorma.entry.tsx"
	],
	publicPathPrefix,
	staticPublicAssetMap,
	buildtimePublicURLFuncName: "hashedURL",
	ignoredPatterns: [
		"**/*.go",
		"**/backend/dist/**/*",
		"**/backend/assets/**/*",
		"**/backend/wave.config.json",
		"**/frontend/src/vorma.gen/**/*",
		"**/frontend/src/vorma.routes.ts"
	],
	dedupeList: [
		"solid-js",
		"solid-js/web"
	],
} as const;
