package tooling

import (
	"bytes"
	"encoding/gob"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/vormadev/vorma/kit/fsutil"
	"github.com/vormadev/vorma/wave"
)

func (b *Builder) loadFileMapFromPath(gobPath string) (wave.FileMap, error) {
	f, err := os.Open(gobPath)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	return fsutil.FromGob[wave.FileMap](f)
}

func (b *Builder) saveFileMap(fm wave.FileMap, gobPath string) error {
	return writeFileAtomic(gobPath, func(f *os.File) error {
		return gob.NewEncoder(f).Encode(fm)
	})
}

func (b *Builder) savePublicFileMapJS(fm wave.FileMap) error {
	simpleMap := make(map[string]string, len(fm))
	for k, v := range fm {
		simpleMap[k] = v.DistName
	}

	jsonBytes, err := json.Marshal(simpleMap)
	if err != nil {
		return err
	}

	content := fmt.Sprintf("export const wavePublicFileMap = %s;", string(jsonBytes))
	hashedName := hashBytes([]byte(content), wave.RelPaths.PublicFileMapJSName())
	_, publishError := publishHashedArtifactWithRef(hashedArtifactPublishOptions{
		log:                   b.log,
		outputDirectoryPath:   b.cfg.Dist.StaticPublic(),
		refFilePath:           b.cfg.Dist.PublicFileMapRef(),
		desiredHashedFileName: hashedName,
		content:               []byte(content),
		globPattern:           wave.FileMapJSGlobPattern,
	})
	return publishError
}

// WritePublicFileMapTS writes the public file map as a TypeScript file to the specified directory.
// This enables Vite HMR to pick up public static file changes without running Go.
func (b *Builder) WritePublicFileMapTS(outDir string) error {
	fm, err := b.loadOrBuildFileMap()
	if err != nil {
		return fmt.Errorf("load file map: %w", err)
	}

	keys := make([]string, 0, len(fm))
	for k := range fm {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("/////// Auto-generated by Wave. Do not edit.\n\n")
	sb.WriteString("export const staticPublicAssetMap = {\n")

	for _, k := range keys {
		v := fm[k]
		sb.WriteString(fmt.Sprintf("\t%q: %q,\n", k, v.DistName))
	}

	sb.WriteString("} as const;\n")

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("create output dir: %w", err)
	}

	outPath := filepath.Join(outDir, wave.RelPaths.PublicFileMapTSName())
	if _, err := writeFileAtomicBytesIfChanged(outPath, []byte(sb.String())); err != nil {
		return fmt.Errorf("write TS file: %w", err)
	}

	if err := b.writePublicFileMapJSON(outDir, fm); err != nil {
		return fmt.Errorf("write JSON file: %w", err)
	}

	return nil
}

// writePublicFileMapJSON writes the public file map as a JSON file for the Vite plugin
// to read in dev mode. This allows the plugin to dynamically reload the filemap
// without restarting Vite.
func (b *Builder) writePublicFileMapJSON(outDir string, fm wave.FileMap) error {
	simpleMap := make(map[string]string, len(fm))
	for k, v := range fm {
		simpleMap[k] = v.DistName
	}

	jsonBytes, err := json.MarshalIndent(simpleMap, "", "\t")
	if err != nil {
		return fmt.Errorf("marshal JSON: %w", err)
	}

	outPath := filepath.Join(outDir, wave.RelPaths.PublicFileMapJSONName())
	_, err = writeFileAtomicBytesIfChanged(outPath, jsonBytes)
	return err
}

// writeFileAtomic writes data to a file atomically using a randomized temp file
// and rename. The write function is called with the temp file to write content.
func writeFileAtomic(path string, write func(*os.File) error) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	tmpFile, err := os.CreateTemp(dir, ".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmpFile.Name()

	success := false
	defer func() {
		if !success {
			os.Remove(tmpPath)
		}
	}()

	if err := write(tmpFile); err != nil {
		tmpFile.Close()
		return err
	}

	if err := tmpFile.Close(); err != nil {
		return err
	}

	if err := os.Rename(tmpPath, path); err != nil {
		return err
	}

	success = true
	return nil
}

func writeFileAtomicBytes(path string, data []byte) error {
	return writeFileAtomic(path, func(f *os.File) error {
		_, err := f.Write(data)
		return err
	})
}

func writeFileAtomicBytesIfChanged(path string, data []byte) (bool, error) {
	existingData, readErr := os.ReadFile(path)
	if readErr == nil {
		if bytes.Equal(existingData, data) {
			return false, nil
		}
	} else if !os.IsNotExist(readErr) {
		return false, readErr
	}

	if err := writeFileAtomicBytes(path, data); err != nil {
		return false, err
	}

	return true, nil
}
