// Code generated by Vorma. DO NOT EDIT.

import type { VormaClientSeed } from "vorma/react";

export const vormaClientSeed = {
	__vorma_views: null as unknown as typeof __vorma_views,
	__vorma_resources: null as unknown as typeof __vorma_resources,
} as const satisfies VormaClientSeed;

declare global {
	/** Argument must be a static string literal. */
	function vormaPublicUrl(k: VormaPublicUrlKey): string;
}

const vormaPublicUrlKeys = ["fonts/IoskeleyMono-400.woff2", "mark.svg"] as const;

type VormaPublicUrlKey = `${"" | "/"}${(typeof vormaPublicUrlKeys)[number]}`;

const __vorma_resources = [
	{
		method: "POST",
		pattern: "/api/notes",
		__i: null as unknown as CreateNoteInput,
		__o: null as unknown as CreateNoteOutput,
	},
	{
		method: "DELETE",
		params: ["note_id"],
		pattern: "/api/notes/:note_id",
		__i: null as unknown as undefined,
		__o: null as unknown as DeleteNoteOutput,
	},
	{
		method: "POST",
		pattern: "/api/notes/import",
		__i: null as unknown as FormData,
		__o: null as unknown as ImportNotesOutput,
	},
	{
		method: "POST",
		params: ["note_id"],
		pattern: "/api/notes/:note_id/duplicate",
		__i: null as unknown as undefined,
		__o: null as unknown as undefined,
	},
	{
		method: "POST",
		pattern: "/api/session",
		__i: null as unknown as LoginInput,
		__o: null as unknown as LoginOutput,
	},
	{
		method: "DELETE",
		pattern: "/api/session",
		__i: null as unknown as undefined,
		__o: null as unknown as undefined,
	},
	{
		method: "GET",
		pattern: "/api/ping",
		__i: null as unknown as undefined,
		__o: null as unknown as PingOutput,
	},
] as const;

const __vorma_views = [
	{
		pattern: "/",
		__i: null as unknown as undefined,
		__o: null as unknown as LayoutData,
	},
	{
		parents: ["/"],
		pattern: "/_index",
		__i: null as unknown as HomeInput,
		__o: null as unknown as HomePage,
	},
	{
		params: ["note_id"],
		parents: ["/"],
		pattern: "/notes/:note_id",
		__i: null as unknown as undefined,
		__o: null as unknown as NotePage,
	},
	{
		parents: ["/"],
		pattern: "/tags/*",
		__i: null as unknown as undefined,
		__o: null as unknown as TagsPage,
	},
	{
		parents: ["/"],
		pattern: "/stats",
		__i: null as unknown as StatsInput,
		__o: null as unknown as StatsPage,
	},
	{
		parents: ["/"],
		pattern: "/admin",
		__i: null as unknown as undefined,
		__o: null as unknown as AdminPage,
	},
	{
		parents: ["/"],
		pattern: "/legacy",
		__i: null as unknown as undefined,
		__o: null as unknown as LegacyPage,
	},
] as const;

export type AdminPage = {
	session: string;
};

export type CreateNoteInput = {
	body: string;
};

export type CreateNoteOutput = {
	note: Note;
};

export type DeleteNoteOutput = {
	deleted: Note;
};

export type HomeInput = {
	draft?: string | null;
};

export type HomePage = {
	draft: string | null;
	notes: Array<Note>;
};

export type ImportNotesOutput = {
	imported: number;
};

export type KeyboardShortcut = {
	keys: string;
	action: string;
};

export type LayoutData = {
	app_name: string;
	mark_url: string;
	signed_in: boolean;
};

export type LegacyPage = Record<never, never>;

export type LoginInput = {
	user: string;
};

export type LoginOutput = {
	session: string;
};

export type Note = {
	id: number;
	body: string;
	tags: Array<string>;
};

export type NotePage = {
	note_id: string;
	note: Note | null;
};

export type PingOutput = {
	ok: boolean;
};

export type StatsInput = {
	fail?: boolean | null;
};

export type StatsPage = {
	note_count: number;
	tag_count: number;
	longest_body_chars: number;
};

export type TagsPage = {
	selected: Array<string>;
	notes: Array<Note>;
	all_tags: Array<string>;
};

export const keyboardShortcuts = [
	{
		action: "focus-composer",
		keys: "mod+k",
	},
] as const;
